//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EvidencniUdaje" type="{http://www.mvcr.cz/nsesss/v2}tEvidencniUdajeDokumentu"/>
 *         &lt;element name="Komponenty" type="{http://www.mvcr.cz/nsesss/v2}tKomponenty" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "evidencniUdaje",
        "komponenty"
})
@XmlRootElement(name = "Dokument", namespace = "http://www.mvcr.cz/nsesss/v2")
public class Dokument {

    @XmlElement(name = "EvidencniUdaje", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TEvidencniUdajeDokumentu evidencniUdaje;
    @XmlElement(name = "Komponenty", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TKomponenty komponenty;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the evidencniUdaje property.
     *
     * @return possible object is
     * {@link TEvidencniUdajeDokumentu }
     *
     */
    public TEvidencniUdajeDokumentu getEvidencniUdaje() {
        return evidencniUdaje;
    }

    /**
     * Sets the value of the evidencniUdaje property.
     *
     * @param value allowed object is
     *              {@link TEvidencniUdajeDokumentu }
     *
     */
    public void setEvidencniUdaje(TEvidencniUdajeDokumentu value) {
        this.evidencniUdaje = value;
    }

    /**
     * Gets the value of the komponenty property.
     *
     * @return possible object is
     * {@link TKomponenty }
     *
     */
    public TKomponenty getKomponenty() {
        return komponenty;
    }

    /**
     * Sets the value of the komponenty property.
     *
     * @param value allowed object is
     *              {@link TKomponenty }
     *
     */
    public void setKomponenty(TKomponenty value) {
        this.komponenty = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setID(String value) {
        this.id = value;
    }

}
