//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.cas.lib.proarc.nsesss2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TSubjektExterniNazevFyzickeOsoby_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "NazevFyzickeOsoby");
    private final static QName _TSubjektExterniOrganizacniUtvar_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "OrganizacniUtvar");
    private final static QName _TSubjektExterniPostovniAdresa_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "PostovniAdresa");
    private final static QName _TSubjektExterniElektronickyKontakt_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "ElektronickyKontakt");
    private final static QName _TSubjektExterniPracovniPozice_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "PracovniPozice");
    private final static QName _TSubjektExterniNazevOrganizace_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "NazevOrganizace");
    private final static QName _TSubjektExterniSidloOrganizace_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "SidloOrganizace");
    private final static QName _TSubjektExterniIdentifikatorFyzickeOsoby_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "IdentifikatorFyzickeOsoby");
    private final static QName _TSubjektExterniIdentifikatorOrganizace_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "IdentifikatorOrganizace");
    private final static QName _TVyrizeniEntityOdkazVyrizujiciDokument_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "OdkazVyrizujiciDokument");
    private final static QName _TVyrizeniEntityOdkazVyrizovanyDokument_QNAME = new QName("http://www.mvcr.cz/nsesss/v2", "OdkazVyrizovanyDokument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.cas.lib.proarc.nsesss2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dil }
     * 
     */
    public Dil createDil() {
        return new Dil();
    }

    /**
     * Create an instance of {@link TEvidencniUdajeDilu }
     * 
     */
    public TEvidencniUdajeDilu createTEvidencniUdajeDilu() {
        return new TEvidencniUdajeDilu();
    }

    /**
     * Create an instance of {@link TDokumenty }
     * 
     */
    public TDokumenty createTDokumenty() {
        return new TDokumenty();
    }

    /**
     * Create an instance of {@link Dokument }
     * 
     */
    public Dokument createDokument() {
        return new Dokument();
    }

    /**
     * Create an instance of {@link TEvidencniUdajeDokumentu }
     * 
     */
    public TEvidencniUdajeDokumentu createTEvidencniUdajeDokumentu() {
        return new TEvidencniUdajeDokumentu();
    }

    /**
     * Create an instance of {@link TKomponenty }
     * 
     */
    public TKomponenty createTKomponenty() {
        return new TKomponenty();
    }

    /**
     * Create an instance of {@link Spis }
     * 
     */
    public Spis createSpis() {
        return new Spis();
    }

    /**
     * Create an instance of {@link TEvidencniUdajeSpisu }
     * 
     */
    public TEvidencniUdajeSpisu createTEvidencniUdajeSpisu() {
        return new TEvidencniUdajeSpisu();
    }

    /**
     * Create an instance of {@link TManipulace }
     * 
     */
    public TManipulace createTManipulace() {
        return new TManipulace();
    }

    /**
     * Create an instance of {@link TOsobyInterni }
     * 
     */
    public TOsobyInterni createTOsobyInterni() {
        return new TOsobyInterni();
    }

    /**
     * Create an instance of {@link TDorucenyDokument }
     * 
     */
    public TDorucenyDokument createTDorucenyDokument() {
        return new TDorucenyDokument();
    }

    /**
     * Create an instance of {@link TVytah }
     * 
     */
    public TVytah createTVytah() {
        return new TVytah();
    }

    /**
     * Create an instance of {@link TOsobaInterni }
     * 
     */
    public TOsobaInterni createTOsobaInterni() {
        return new TOsobaInterni();
    }

    /**
     * Create an instance of {@link TManipulaceSpisovyPlan }
     * 
     */
    public TManipulaceSpisovyPlan createTManipulaceSpisovyPlan() {
        return new TManipulaceSpisovyPlan();
    }

    /**
     * Create an instance of {@link TPlatnost }
     * 
     */
    public TPlatnost createTPlatnost() {
        return new TPlatnost();
    }

    /**
     * Create an instance of {@link TPrevodDokumentu }
     * 
     */
    public TPrevodDokumentu createTPrevodDokumentu() {
        return new TPrevodDokumentu();
    }

    /**
     * Create an instance of {@link TSchvalovani }
     * 
     */
    public TSchvalovani createTSchvalovani() {
        return new TSchvalovani();
    }

    /**
     * Create an instance of {@link TKlicovaSlova }
     * 
     */
    public TKlicovaSlova createTKlicovaSlova() {
        return new TKlicovaSlova();
    }

    /**
     * Create an instance of {@link TSpisovyPlan }
     * 
     */
    public TSpisovyPlan createTSpisovyPlan() {
        return new TSpisovyPlan();
    }

    /**
     * Create an instance of {@link TSubjektExterni }
     * 
     */
    public TSubjektExterni createTSubjektExterni() {
        return new TSubjektExterni();
    }

    /**
     * Create an instance of {@link TBezpecnostniKategorie }
     * 
     */
    public TBezpecnostniKategorie createTBezpecnostniKategorie() {
        return new TBezpecnostniKategorie();
    }

    /**
     * Create an instance of {@link TEvidencniUdajeKomponenty }
     * 
     */
    public TEvidencniUdajeKomponenty createTEvidencniUdajeKomponenty() {
        return new TEvidencniUdajeKomponenty();
    }

    /**
     * Create an instance of {@link TTypovySpis }
     * 
     */
    public TTypovySpis createTTypovySpis() {
        return new TTypovySpis();
    }

    /**
     * Create an instance of {@link TNeevidence }
     * 
     */
    public TNeevidence createTNeevidence() {
        return new TNeevidence();
    }

    /**
     * Create an instance of {@link TPristupnost }
     * 
     */
    public TPristupnost createTPristupnost() {
        return new TPristupnost();
    }

    /**
     * Create an instance of {@link TTrideniSoucasti }
     * 
     */
    public TTrideniSoucasti createTTrideniSoucasti() {
        return new TTrideniSoucasti();
    }

    /**
     * Create an instance of {@link TSchvaleni }
     * 
     */
    public TSchvaleni createTSchvaleni() {
        return new TSchvaleni();
    }

    /**
     * Create an instance of {@link TTrideniVecneSkupiny }
     * 
     */
    public TTrideniVecneSkupiny createTTrideniVecneSkupiny() {
        return new TTrideniVecneSkupiny();
    }

    /**
     * Create an instance of {@link TSoucast }
     * 
     */
    public TSoucast createTSoucast() {
        return new TSoucast();
    }

    /**
     * Create an instance of {@link TVystup }
     * 
     */
    public TVystup createTVystup() {
        return new TVystup();
    }

    /**
     * Create an instance of {@link TPuvodSeskupeni }
     * 
     */
    public TPuvodSeskupeni createTPuvodSeskupeni() {
        return new TPuvodSeskupeni();
    }

    /**
     * Create an instance of {@link TVyrizeni }
     * 
     */
    public TVyrizeni createTVyrizeni() {
        return new TVyrizeni();
    }

    /**
     * Create an instance of {@link TPrevodKomponenty }
     * 
     */
    public TPrevodKomponenty createTPrevodKomponenty() {
        return new TPrevodKomponenty();
    }

    /**
     * Create an instance of {@link TOvereniCertifikatu }
     * 
     */
    public TOvereniCertifikatu createTOvereniCertifikatu() {
        return new TOvereniCertifikatu();
    }

    /**
     * Create an instance of {@link TPopis }
     * 
     */
    public TPopis createTPopis() {
        return new TPopis();
    }

    /**
     * Create an instance of {@link TTrideniDilu }
     * 
     */
    public TTrideniDilu createTTrideniDilu() {
        return new TTrideniDilu();
    }

    /**
     * Create an instance of {@link TJazyky }
     * 
     */
    public TJazyky createTJazyky() {
        return new TJazyky();
    }

    /**
     * Create an instance of {@link TKonverzeADDA }
     * 
     */
    public TKonverzeADDA createTKonverzeADDA() {
        return new TKonverzeADDA();
    }

    /**
     * Create an instance of {@link TIdentifikace }
     * 
     */
    public TIdentifikace createTIdentifikace() {
        return new TIdentifikace();
    }

    /**
     * Create an instance of {@link TOdkaz }
     * 
     */
    public TOdkaz createTOdkaz() {
        return new TOdkaz();
    }

    /**
     * Create an instance of {@link TOsobaExterni }
     * 
     */
    public TOsobaExterni createTOsobaExterni() {
        return new TOsobaExterni();
    }

    /**
     * Create an instance of {@link TIdentifikator }
     * 
     */
    public TIdentifikator createTIdentifikator() {
        return new TIdentifikator();
    }

    /**
     * Create an instance of {@link TEvidencniUdajeSoucasti }
     * 
     */
    public TEvidencniUdajeSoucasti createTEvidencniUdajeSoucasti() {
        return new TEvidencniUdajeSoucasti();
    }

    /**
     * Create an instance of {@link TTypDokumentu }
     * 
     */
    public TTypDokumentu createTTypDokumentu() {
        return new TTypDokumentu();
    }

    /**
     * Create an instance of {@link TVyrazovani }
     * 
     */
    public TVyrazovani createTVyrazovani() {
        return new TVyrazovani();
    }

    /**
     * Create an instance of {@link TOsobyExterni }
     * 
     */
    public TOsobyExterni createTOsobyExterni() {
        return new TOsobyExterni();
    }

    /**
     * Create an instance of {@link TTrideniTypovehoSpisu }
     * 
     */
    public TTrideniTypovehoSpisu createTTrideniTypovehoSpisu() {
        return new TTrideniTypovehoSpisu();
    }

    /**
     * Create an instance of {@link TMaterskaEntitaVecneSkupiny }
     * 
     */
    public TMaterskaEntitaVecneSkupiny createTMaterskaEntitaVecneSkupiny() {
        return new TMaterskaEntitaVecneSkupiny();
    }

    /**
     * Create an instance of {@link TTrideniDokumentu }
     * 
     */
    public TTrideniDokumentu createTTrideniDokumentu() {
        return new TTrideniDokumentu();
    }

    /**
     * Create an instance of {@link TDatum }
     * 
     */
    public TDatum createTDatum() {
        return new TDatum();
    }

    /**
     * Create an instance of {@link TManipulaceDokumentu }
     * 
     */
    public TManipulaceDokumentu createTManipulaceDokumentu() {
        return new TManipulaceDokumentu();
    }

    /**
     * Create an instance of {@link TEvidencniUdajeTypovehoSpisu }
     * 
     */
    public TEvidencniUdajeTypovehoSpisu createTEvidencniUdajeTypovehoSpisu() {
        return new TEvidencniUdajeTypovehoSpisu();
    }

    /**
     * Create an instance of {@link TManipulaceKomponenty }
     * 
     */
    public TManipulaceKomponenty createTManipulaceKomponenty() {
        return new TManipulaceKomponenty();
    }

    /**
     * Create an instance of {@link TRedakce }
     * 
     */
    public TRedakce createTRedakce() {
        return new TRedakce();
    }

    /**
     * Create an instance of {@link TTrideniSpisu }
     * 
     */
    public TTrideniSpisu createTTrideniSpisu() {
        return new TTrideniSpisu();
    }

    /**
     * Create an instance of {@link TSkartacniRizeni }
     * 
     */
    public TSkartacniRizeni createTSkartacniRizeni() {
        return new TSkartacniRizeni();
    }

    /**
     * Create an instance of {@link TVlastniDokument }
     * 
     */
    public TVlastniDokument createTVlastniDokument() {
        return new TVlastniDokument();
    }

    /**
     * Create an instance of {@link TOvereniBezpecnostnihoPrvku }
     * 
     */
    public TOvereniBezpecnostnihoPrvku createTOvereniBezpecnostnihoPrvku() {
        return new TOvereniBezpecnostnihoPrvku();
    }

    /**
     * Create an instance of {@link TMaterskaEntitaTypovehoSpisu }
     * 
     */
    public TMaterskaEntitaTypovehoSpisu createTMaterskaEntitaTypovehoSpisu() {
        return new TMaterskaEntitaTypovehoSpisu();
    }

    /**
     * Create an instance of {@link TPuvodDokumentu }
     * 
     */
    public TPuvodDokumentu createTPuvodDokumentu() {
        return new TPuvodDokumentu();
    }

    /**
     * Create an instance of {@link TMaterskeEntityDokumentu }
     * 
     */
    public TMaterskeEntityDokumentu createTMaterskeEntityDokumentu() {
        return new TMaterskeEntityDokumentu();
    }

    /**
     * Create an instance of {@link TVyrizeniEntity }
     * 
     */
    public TVyrizeniEntity createTVyrizeniEntity() {
        return new TVyrizeniEntity();
    }

    /**
     * Create an instance of {@link TJineUdaje }
     * 
     */
    public TJineUdaje createTJineUdaje() {
        return new TJineUdaje();
    }

    /**
     * Create an instance of {@link TZtvarneni }
     * 
     */
    public TZtvarneni createTZtvarneni() {
        return new TZtvarneni();
    }

    /**
     * Create an instance of {@link TSubjektInterni }
     * 
     */
    public TSubjektInterni createTSubjektInterni() {
        return new TSubjektInterni();
    }

    /**
     * Create an instance of {@link TEvidencniUdajeVecneSkupiny }
     * 
     */
    public TEvidencniUdajeVecneSkupiny createTEvidencniUdajeVecneSkupiny() {
        return new TEvidencniUdajeVecneSkupiny();
    }

    /**
     * Create an instance of {@link TUrceneCasoveObdobi }
     * 
     */
    public TUrceneCasoveObdobi createTUrceneCasoveObdobi() {
        return new TUrceneCasoveObdobi();
    }

    /**
     * Create an instance of {@link TKonverzeDD }
     * 
     */
    public TKonverzeDD createTKonverzeDD() {
        return new TKonverzeDD();
    }

    /**
     * Create an instance of {@link TDataceVyrazeni }
     * 
     */
    public TDataceVyrazeni createTDataceVyrazeni() {
        return new TDataceVyrazeni();
    }

    /**
     * Create an instance of {@link TPoznamky }
     * 
     */
    public TPoznamky createTPoznamky() {
        return new TPoznamky();
    }

    /**
     * Create an instance of {@link TKomponenta }
     * 
     */
    public TKomponenta createTKomponenta() {
        return new TKomponenta();
    }

    /**
     * Create an instance of {@link TEvidence }
     * 
     */
    public TEvidence createTEvidence() {
        return new TEvidence();
    }

    /**
     * Create an instance of {@link TMaterskaEntitaDilu }
     * 
     */
    public TMaterskaEntitaDilu createTMaterskaEntitaDilu() {
        return new TMaterskaEntitaDilu();
    }

    /**
     * Create an instance of {@link TMaterskaEntitaSpisu }
     * 
     */
    public TMaterskaEntitaSpisu createTMaterskaEntitaSpisu() {
        return new TMaterskaEntitaSpisu();
    }

    /**
     * Create an instance of {@link TCertifikat }
     * 
     */
    public TCertifikat createTCertifikat() {
        return new TCertifikat();
    }

    /**
     * Create an instance of {@link TSkartacniRezim }
     * 
     */
    public TSkartacniRezim createTSkartacniRezim() {
        return new TSkartacniRezim();
    }

    /**
     * Create an instance of {@link TVecnaSkupina }
     * 
     */
    public TVecnaSkupina createTVecnaSkupina() {
        return new TVecnaSkupina();
    }

    /**
     * Create an instance of {@link TUzavreni }
     * 
     */
    public TUzavreni createTUzavreni() {
        return new TUzavreni();
    }

    /**
     * Create an instance of {@link TMaterskaEntitaSoucasti }
     * 
     */
    public TMaterskaEntitaSoucasti createTMaterskaEntitaSoucasti() {
        return new TMaterskaEntitaSoucasti();
    }

    /**
     * Create an instance of {@link TManipulaceSeskupeni }
     * 
     */
    public TManipulaceSeskupeni createTManipulaceSeskupeni() {
        return new TManipulaceSeskupeni();
    }

    /**
     * Create an instance of {@link TTrideni }
     * 
     */
    public TTrideni createTTrideni() {
        return new TTrideni();
    }

    /**
     * Create an instance of {@link TSouvislosti }
     * 
     */
    public TSouvislosti createTSouvislosti() {
        return new TSouvislosti();
    }

    /**
     * Create an instance of {@link TPopisKomponenty }
     * 
     */
    public TPopisKomponenty createTPopisKomponenty() {
        return new TPopisKomponenty();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "NazevFyzickeOsoby", scope = TSubjektExterni.class)
    public JAXBElement<String> createTSubjektExterniNazevFyzickeOsoby(String value) {
        return new JAXBElement<String>(_TSubjektExterniNazevFyzickeOsoby_QNAME, String.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "OrganizacniUtvar", scope = TSubjektExterni.class)
    public JAXBElement<String> createTSubjektExterniOrganizacniUtvar(String value) {
        return new JAXBElement<String>(_TSubjektExterniOrganizacniUtvar_QNAME, String.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "PostovniAdresa", scope = TSubjektExterni.class)
    public JAXBElement<String> createTSubjektExterniPostovniAdresa(String value) {
        return new JAXBElement<String>(_TSubjektExterniPostovniAdresa_QNAME, String.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "ElektronickyKontakt", scope = TSubjektExterni.class)
    public JAXBElement<String> createTSubjektExterniElektronickyKontakt(String value) {
        return new JAXBElement<String>(_TSubjektExterniElektronickyKontakt_QNAME, String.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "PracovniPozice", scope = TSubjektExterni.class)
    public JAXBElement<String> createTSubjektExterniPracovniPozice(String value) {
        return new JAXBElement<String>(_TSubjektExterniPracovniPozice_QNAME, String.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "NazevOrganizace", scope = TSubjektExterni.class)
    public JAXBElement<String> createTSubjektExterniNazevOrganizace(String value) {
        return new JAXBElement<String>(_TSubjektExterniNazevOrganizace_QNAME, String.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "SidloOrganizace", scope = TSubjektExterni.class)
    public JAXBElement<String> createTSubjektExterniSidloOrganizace(String value) {
        return new JAXBElement<String>(_TSubjektExterniSidloOrganizace_QNAME, String.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIdentifikator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "IdentifikatorFyzickeOsoby", scope = TSubjektExterni.class)
    public JAXBElement<TIdentifikator> createTSubjektExterniIdentifikatorFyzickeOsoby(TIdentifikator value) {
        return new JAXBElement<TIdentifikator>(_TSubjektExterniIdentifikatorFyzickeOsoby_QNAME, TIdentifikator.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIdentifikator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "IdentifikatorOrganizace", scope = TSubjektExterni.class)
    public JAXBElement<TIdentifikator> createTSubjektExterniIdentifikatorOrganizace(TIdentifikator value) {
        return new JAXBElement<TIdentifikator>(_TSubjektExterniIdentifikatorOrganizace_QNAME, TIdentifikator.class, TSubjektExterni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOdkaz }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "OdkazVyrizujiciDokument", scope = TVyrizeniEntity.class)
    public JAXBElement<TOdkaz> createTVyrizeniEntityOdkazVyrizujiciDokument(TOdkaz value) {
        return new JAXBElement<TOdkaz>(_TVyrizeniEntityOdkazVyrizujiciDokument_QNAME, TOdkaz.class, TVyrizeniEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOdkaz }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mvcr.cz/nsesss/v2", name = "OdkazVyrizovanyDokument", scope = TVyrizeniEntity.class)
    public JAXBElement<TOdkaz> createTVyrizeniEntityOdkazVyrizovanyDokument(TOdkaz value) {
        return new JAXBElement<TOdkaz>(_TVyrizeniEntityOdkazVyrizovanyDokument_QNAME, TOdkaz.class, TVyrizeniEntity.class, value);
    }

}
