//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tCertifikat complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tCertifikat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SerioveCislo" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator"/>
 *         &lt;element name="Vydavatel" type="{http://www.mvcr.cz/nsesss/v2}tOsobaExterni"/>
 *         &lt;element name="Držitel" type="{http://www.mvcr.cz/nsesss/v2}tOsobaExterni"/>
 *         &lt;element name="Platnost" type="{http://www.mvcr.cz/nsesss/v2}tPlatnost"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCertifikat", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "serioveCislo",
        "vydavatel",
        "dr\u017eitel",
        "platnost"
})
public class TCertifikat {

    @XmlElement(name = "SerioveCislo", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TIdentifikator serioveCislo;
    @XmlElement(name = "Vydavatel", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOsobaExterni vydavatel;
    @XmlElement(name = "Dr\u017eitel", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOsobaExterni držitel;
    @XmlElement(name = "Platnost", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TPlatnost platnost;

    /**
     * Gets the value of the serioveCislo property.
     *
     * @return possible object is
     * {@link TIdentifikator }
     *
     */
    public TIdentifikator getSerioveCislo() {
        return serioveCislo;
    }

    /**
     * Sets the value of the serioveCislo property.
     *
     * @param value allowed object is
     *              {@link TIdentifikator }
     *
     */
    public void setSerioveCislo(TIdentifikator value) {
        this.serioveCislo = value;
    }

    /**
     * Gets the value of the vydavatel property.
     *
     * @return possible object is
     * {@link TOsobaExterni }
     *
     */
    public TOsobaExterni getVydavatel() {
        return vydavatel;
    }

    /**
     * Sets the value of the vydavatel property.
     *
     * @param value allowed object is
     *              {@link TOsobaExterni }
     *
     */
    public void setVydavatel(TOsobaExterni value) {
        this.vydavatel = value;
    }

    /**
     * Gets the value of the držitel property.
     *
     * @return possible object is
     * {@link TOsobaExterni }
     *
     */
    public TOsobaExterni getDržitel() {
        return držitel;
    }

    /**
     * Sets the value of the držitel property.
     *
     * @param value allowed object is
     *              {@link TOsobaExterni }
     *
     */
    public void setDržitel(TOsobaExterni value) {
        this.držitel = value;
    }

    /**
     * Gets the value of the platnost property.
     *
     * @return possible object is
     * {@link TPlatnost }
     *
     */
    public TPlatnost getPlatnost() {
        return platnost;
    }

    /**
     * Sets the value of the platnost property.
     *
     * @param value allowed object is
     *              {@link TPlatnost }
     *
     */
    public void setPlatnost(TPlatnost value) {
        this.platnost = value;
    }

}
