//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Časové údaje evidující počátek a konec plynutí skartační lhůty.
 *
 * <p>Java class for tDataceVyrazeni complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tDataceVyrazeni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RokSpousteciUdalosti" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         &lt;element name="RokSkartacniOperace" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDataceVyrazeni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "rokSpousteciUdalosti",
        "rokSkartacniOperace"
})
public class TDataceVyrazeni {

    @XmlElement(name = "RokSpousteciUdalosti", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar rokSpousteciUdalosti;
    @XmlElement(name = "RokSkartacniOperace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar rokSkartacniOperace;

    /**
     * Gets the value of the rokSpousteciUdalosti property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getRokSpousteciUdalosti() {
        return rokSpousteciUdalosti;
    }

    /**
     * Sets the value of the rokSpousteciUdalosti property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setRokSpousteciUdalosti(XMLGregorianCalendar value) {
        this.rokSpousteciUdalosti = value;
    }

    /**
     * Gets the value of the rokSkartacniOperace property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getRokSkartacniOperace() {
        return rokSkartacniOperace;
    }

    /**
     * Sets the value of the rokSkartacniOperace property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setRokSkartacniOperace(XMLGregorianCalendar value) {
        this.rokSkartacniOperace = value;
    }

}
