//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro evidenční údaje entity "komponenta".
 *
 * <p>Java class for tEvidencniUdajeKomponenty complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tEvidencniUdajeKomponenty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifikace" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikace"/>
 *         &lt;element name="Popis" type="{http://www.mvcr.cz/nsesss/v2}tPopisKomponenty"/>
 *         &lt;element name="Trideni" type="{http://www.mvcr.cz/nsesss/v2}tTrideni"/>
 *         &lt;element name="Manipulace" type="{http://www.mvcr.cz/nsesss/v2}tManipulaceKomponenty" minOccurs="0"/>
 *         &lt;element name="Prevod" type="{http://www.mvcr.cz/nsesss/v2}tPrevodKomponenty" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEvidencniUdajeKomponenty", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "identifikace",
        "popis",
        "trideni",
        "manipulace",
        "prevod"
})
public class TEvidencniUdajeKomponenty {

    @XmlElement(name = "Identifikace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TIdentifikace identifikace;
    @XmlElement(name = "Popis", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TPopisKomponenty popis;
    @XmlElement(name = "Trideni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TTrideni trideni;
    @XmlElement(name = "Manipulace", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TManipulaceKomponenty manipulace;
    @XmlElement(name = "Prevod", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TPrevodKomponenty prevod;

    /**
     * Gets the value of the identifikace property.
     *
     * @return possible object is
     * {@link TIdentifikace }
     *
     */
    public TIdentifikace getIdentifikace() {
        return identifikace;
    }

    /**
     * Sets the value of the identifikace property.
     *
     * @param value allowed object is
     *              {@link TIdentifikace }
     *
     */
    public void setIdentifikace(TIdentifikace value) {
        this.identifikace = value;
    }

    /**
     * Gets the value of the popis property.
     *
     * @return possible object is
     * {@link TPopisKomponenty }
     *
     */
    public TPopisKomponenty getPopis() {
        return popis;
    }

    /**
     * Sets the value of the popis property.
     *
     * @param value allowed object is
     *              {@link TPopisKomponenty }
     *
     */
    public void setPopis(TPopisKomponenty value) {
        this.popis = value;
    }

    /**
     * Gets the value of the trideni property.
     *
     * @return possible object is
     * {@link TTrideni }
     *
     */
    public TTrideni getTrideni() {
        return trideni;
    }

    /**
     * Sets the value of the trideni property.
     *
     * @param value allowed object is
     *              {@link TTrideni }
     *
     */
    public void setTrideni(TTrideni value) {
        this.trideni = value;
    }

    /**
     * Gets the value of the manipulace property.
     *
     * @return possible object is
     * {@link TManipulaceKomponenty }
     *
     */
    public TManipulaceKomponenty getManipulace() {
        return manipulace;
    }

    /**
     * Sets the value of the manipulace property.
     *
     * @param value allowed object is
     *              {@link TManipulaceKomponenty }
     *
     */
    public void setManipulace(TManipulaceKomponenty value) {
        this.manipulace = value;
    }

    /**
     * Gets the value of the prevod property.
     *
     * @return possible object is
     * {@link TPrevodKomponenty }
     *
     */
    public TPrevodKomponenty getPrevod() {
        return prevod;
    }

    /**
     * Sets the value of the prevod property.
     *
     * @param value allowed object is
     *              {@link TPrevodKomponenty }
     *
     */
    public void setPrevod(TPrevodKomponenty value) {
        this.prevod = value;
    }

}
