//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro evidenční údaje entity "dokument".
 *
 * <p>Java class for tEvidencniUdajeDokumentu complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tEvidencniUdajeDokumentu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.mvcr.cz/nsesss/v2}tEntita"/>
 *         &lt;choice>
 *           &lt;element name="Evidence" type="{http://www.mvcr.cz/nsesss/v2}tEvidence"/>
 *           &lt;element name="Neevidence" type="{http://www.mvcr.cz/nsesss/v2}tNeevidence"/>
 *         &lt;/choice>
 *         &lt;element name="Jazyky" type="{http://www.mvcr.cz/nsesss/v2}tJazyky" minOccurs="0"/>
 *         &lt;element name="Puvod" type="{http://www.mvcr.cz/nsesss/v2}tPuvodDokumentu"/>
 *         &lt;element name="Trideni" type="{http://www.mvcr.cz/nsesss/v2}tTrideniDokumentu"/>
 *         &lt;element name="Vyrizeni" type="{http://www.mvcr.cz/nsesss/v2}tVyrizeniEntity" minOccurs="0"/>
 *         &lt;element name="Vyrazovani" type="{http://www.mvcr.cz/nsesss/v2}tVyrazovani"/>
 *         &lt;element name="Manipulace" type="{http://www.mvcr.cz/nsesss/v2}tManipulaceDokumentu"/>
 *         &lt;element name="Prevod" type="{http://www.mvcr.cz/nsesss/v2}tPrevodDokumentu" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEvidencniUdajeDokumentu", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "identifikace",
        "popis",
        "souvislosti",
        "pristupnost",
        "poznamky",
        "jineUdaje",
        "evidence",
        "neevidence",
        "jazyky",
        "puvod",
        "trideni",
        "vyrizeni",
        "vyrazovani",
        "manipulace",
        "prevod"
})
public class TEvidencniUdajeDokumentu {

    @XmlElement(name = "Identifikace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TIdentifikace identifikace;
    @XmlElement(name = "Popis", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TPopis popis;
    @XmlElement(name = "Souvislosti", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TSouvislosti souvislosti;
    @XmlElement(name = "Pristupnost", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TPristupnost pristupnost;
    @XmlElement(name = "Poznamky", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TPoznamky poznamky;
    @XmlElement(name = "JineUdaje", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TJineUdaje jineUdaje;
    @XmlElement(name = "Evidence", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TEvidence evidence;
    @XmlElement(name = "Neevidence", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TNeevidence neevidence;
    @XmlElement(name = "Jazyky", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TJazyky jazyky;
    @XmlElement(name = "Puvod", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TPuvodDokumentu puvod;
    @XmlElement(name = "Trideni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TTrideniDokumentu trideni;
    @XmlElement(name = "Vyrizeni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TVyrizeniEntity vyrizeni;
    @XmlElement(name = "Vyrazovani", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TVyrazovani vyrazovani;
    @XmlElement(name = "Manipulace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TManipulaceDokumentu manipulace;
    @XmlElement(name = "Prevod", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TPrevodDokumentu prevod;

    /**
     * Gets the value of the identifikace property.
     *
     * @return possible object is
     * {@link TIdentifikace }
     *
     */
    public TIdentifikace getIdentifikace() {
        return identifikace;
    }

    /**
     * Sets the value of the identifikace property.
     *
     * @param value allowed object is
     *              {@link TIdentifikace }
     *
     */
    public void setIdentifikace(TIdentifikace value) {
        this.identifikace = value;
    }

    /**
     * Gets the value of the popis property.
     *
     * @return possible object is
     * {@link TPopis }
     *
     */
    public TPopis getPopis() {
        return popis;
    }

    /**
     * Sets the value of the popis property.
     *
     * @param value allowed object is
     *              {@link TPopis }
     *
     */
    public void setPopis(TPopis value) {
        this.popis = value;
    }

    /**
     * Gets the value of the souvislosti property.
     *
     * @return possible object is
     * {@link TSouvislosti }
     *
     */
    public TSouvislosti getSouvislosti() {
        return souvislosti;
    }

    /**
     * Sets the value of the souvislosti property.
     *
     * @param value allowed object is
     *              {@link TSouvislosti }
     *
     */
    public void setSouvislosti(TSouvislosti value) {
        this.souvislosti = value;
    }

    /**
     * Gets the value of the pristupnost property.
     *
     * @return possible object is
     * {@link TPristupnost }
     *
     */
    public TPristupnost getPristupnost() {
        return pristupnost;
    }

    /**
     * Sets the value of the pristupnost property.
     *
     * @param value allowed object is
     *              {@link TPristupnost }
     *
     */
    public void setPristupnost(TPristupnost value) {
        this.pristupnost = value;
    }

    /**
     * Gets the value of the poznamky property.
     *
     * @return possible object is
     * {@link TPoznamky }
     *
     */
    public TPoznamky getPoznamky() {
        return poznamky;
    }

    /**
     * Sets the value of the poznamky property.
     *
     * @param value allowed object is
     *              {@link TPoznamky }
     *
     */
    public void setPoznamky(TPoznamky value) {
        this.poznamky = value;
    }

    /**
     * Gets the value of the jineUdaje property.
     *
     * @return possible object is
     * {@link TJineUdaje }
     *
     */
    public TJineUdaje getJineUdaje() {
        return jineUdaje;
    }

    /**
     * Sets the value of the jineUdaje property.
     *
     * @param value allowed object is
     *              {@link TJineUdaje }
     *
     */
    public void setJineUdaje(TJineUdaje value) {
        this.jineUdaje = value;
    }

    /**
     * Gets the value of the evidence property.
     *
     * @return possible object is
     * {@link TEvidence }
     *
     */
    public TEvidence getEvidence() {
        return evidence;
    }

    /**
     * Sets the value of the evidence property.
     *
     * @param value allowed object is
     *              {@link TEvidence }
     *
     */
    public void setEvidence(TEvidence value) {
        this.evidence = value;
    }

    /**
     * Gets the value of the neevidence property.
     *
     * @return possible object is
     * {@link TNeevidence }
     *
     */
    public TNeevidence getNeevidence() {
        return neevidence;
    }

    /**
     * Sets the value of the neevidence property.
     *
     * @param value allowed object is
     *              {@link TNeevidence }
     *
     */
    public void setNeevidence(TNeevidence value) {
        this.neevidence = value;
    }

    /**
     * Gets the value of the jazyky property.
     *
     * @return possible object is
     * {@link TJazyky }
     *
     */
    public TJazyky getJazyky() {
        return jazyky;
    }

    /**
     * Sets the value of the jazyky property.
     *
     * @param value allowed object is
     *              {@link TJazyky }
     *
     */
    public void setJazyky(TJazyky value) {
        this.jazyky = value;
    }

    /**
     * Gets the value of the puvod property.
     *
     * @return possible object is
     * {@link TPuvodDokumentu }
     *
     */
    public TPuvodDokumentu getPuvod() {
        return puvod;
    }

    /**
     * Sets the value of the puvod property.
     *
     * @param value allowed object is
     *              {@link TPuvodDokumentu }
     *
     */
    public void setPuvod(TPuvodDokumentu value) {
        this.puvod = value;
    }

    /**
     * Gets the value of the trideni property.
     *
     * @return possible object is
     * {@link TTrideniDokumentu }
     *
     */
    public TTrideniDokumentu getTrideni() {
        return trideni;
    }

    /**
     * Sets the value of the trideni property.
     *
     * @param value allowed object is
     *              {@link TTrideniDokumentu }
     *
     */
    public void setTrideni(TTrideniDokumentu value) {
        this.trideni = value;
    }

    /**
     * Gets the value of the vyrizeni property.
     *
     * @return possible object is
     * {@link TVyrizeniEntity }
     *
     */
    public TVyrizeniEntity getVyrizeni() {
        return vyrizeni;
    }

    /**
     * Sets the value of the vyrizeni property.
     *
     * @param value allowed object is
     *              {@link TVyrizeniEntity }
     *
     */
    public void setVyrizeni(TVyrizeniEntity value) {
        this.vyrizeni = value;
    }

    /**
     * Gets the value of the vyrazovani property.
     *
     * @return possible object is
     * {@link TVyrazovani }
     *
     */
    public TVyrazovani getVyrazovani() {
        return vyrazovani;
    }

    /**
     * Sets the value of the vyrazovani property.
     *
     * @param value allowed object is
     *              {@link TVyrazovani }
     *
     */
    public void setVyrazovani(TVyrazovani value) {
        this.vyrazovani = value;
    }

    /**
     * Gets the value of the manipulace property.
     *
     * @return possible object is
     * {@link TManipulaceDokumentu }
     *
     */
    public TManipulaceDokumentu getManipulace() {
        return manipulace;
    }

    /**
     * Sets the value of the manipulace property.
     *
     * @param value allowed object is
     *              {@link TManipulaceDokumentu }
     *
     */
    public void setManipulace(TManipulaceDokumentu value) {
        this.manipulace = value;
    }

    /**
     * Gets the value of the prevod property.
     *
     * @return possible object is
     * {@link TPrevodDokumentu }
     *
     */
    public TPrevodDokumentu getPrevod() {
        return prevod;
    }

    /**
     * Sets the value of the prevod property.
     *
     * @param value allowed object is
     *              {@link TPrevodDokumentu }
     *
     */
    public void setPrevod(TPrevodDokumentu value) {
        this.prevod = value;
    }

}
