//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro popis konverze komponenty z digitální podoby do jiné digitální podoby (DD). V terminologii jiné profesní oblasti se jedná o migraci komponenty.
 *
 * <p>Java class for tKonverzeDD complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tKonverzeDD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Ztvarneni" type="{http://www.mvcr.cz/nsesss/v2}tZtvarneni" maxOccurs="unbounded"/>
 *         &lt;sequence>
 *           &lt;element name="Oduvodneni" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="OdkazPuvodniKomponenta" type="{http://www.mvcr.cz/nsesss/v2}tOdkaz" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tKonverzeDD", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "ztvarneni",
        "oduvodneni",
        "odkazPuvodniKomponenta"
})
public class TKonverzeDD {

    @XmlElement(name = "Ztvarneni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected List<TZtvarneni> ztvarneni;
    @XmlElement(name = "Oduvodneni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String oduvodneni;
    @XmlElement(name = "OdkazPuvodniKomponenta", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected List<TOdkaz> odkazPuvodniKomponenta;

    /**
     * Gets the value of the ztvarneni property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ztvarneni property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZtvarneni().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TZtvarneni }
     *
     *
     */
    public List<TZtvarneni> getZtvarneni() {
        if (ztvarneni == null) {
            ztvarneni = new ArrayList<TZtvarneni>();
        }
        return this.ztvarneni;
    }

    /**
     * Gets the value of the oduvodneni property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getOduvodneni() {
        return oduvodneni;
    }

    /**
     * Sets the value of the oduvodneni property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setOduvodneni(String value) {
        this.oduvodneni = value;
    }

    /**
     * Gets the value of the odkazPuvodniKomponenta property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the odkazPuvodniKomponenta property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOdkazPuvodniKomponenta().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TOdkaz }
     *
     *
     */
    public List<TOdkaz> getOdkazPuvodniKomponenta() {
        if (odkazPuvodniKomponenta == null) {
            odkazPuvodniKomponenta = new ArrayList<TOdkaz>();
        }
        return this.odkazPuvodniKomponenta;
    }

}
