//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro indikaci nezbytných dokumentů a dokumentů v analogové podobě. Prvek obsahuje volitelnou identifikaci externího subjektu, který zajišťuje správu dokumentů (například dodavatele hostovaného řešení digitálního úložiště nebo komerční spisovnu dokumentů v analogové podobě).
 * 
 * <p>Java class for tManipulaceDokumentu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tManipulaceDokumentu">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mvcr.cz/nsesss/v2}tManipulace">
 *       &lt;sequence>
 *         &lt;element name="SpravceSpisovny" type="{http://www.mvcr.cz/nsesss/v2}tOsobyExterni" minOccurs="0"/>
 *         &lt;element name="UkladaciJednotka" type="{http://www.mvcr.cz/nsesss/v2}tUkladaciJednotka" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tManipulaceDokumentu", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "spravceSpisovny",
    "ukladaciJednotka"
})
public class TManipulaceDokumentu
    extends TManipulace
{

    @XmlElement(name = "SpravceSpisovny", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TOsobyExterni spravceSpisovny;
    @XmlElement(name = "UkladaciJednotka", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String ukladaciJednotka;

    /**
     * Gets the value of the spravceSpisovny property.
     * 
     * @return
     *     possible object is
     *     {@link TOsobyExterni }
     *     
     */
    public TOsobyExterni getSpravceSpisovny() {
        return spravceSpisovny;
    }

    /**
     * Sets the value of the spravceSpisovny property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsobyExterni }
     *     
     */
    public void setSpravceSpisovny(TOsobyExterni value) {
        this.spravceSpisovny = value;
    }

    /**
     * Gets the value of the ukladaciJednotka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUkladaciJednotka() {
        return ukladaciJednotka;
    }

    /**
     * Sets the value of the ukladaciJednotka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUkladaciJednotka(String value) {
        this.ukladaciJednotka = value;
    }

}
