//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro indikaci nezbytných dokumentů a dokumentů v analogové podobě. Prvek obsahuje povinné časové údaje evidující otevření a uzavření entity pro příjem dceřiných entit.
 *
 * <p>Java class for tManipulaceSeskupeni complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tManipulaceSeskupeni">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mvcr.cz/nsesss/v2}tManipulace">
 *       &lt;sequence>
 *         &lt;element name="DatumOtevreni" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="DatumUzavreni" type="{http://www.mvcr.cz/nsesss/v2}tDatum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tManipulaceSeskupeni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "datumOtevreni",
        "datumUzavreni"
})
public class TManipulaceSeskupeni
        extends TManipulace {

    @XmlElement(name = "DatumOtevreni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum datumOtevreni;
    @XmlElement(name = "DatumUzavreni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TDatum datumUzavreni;

    /**
     * Gets the value of the datumOtevreni property.
     *
     * @return possible object is
     * {@link TDatum }
     *
     */
    public TDatum getDatumOtevreni() {
        return datumOtevreni;
    }

    /**
     * Sets the value of the datumOtevreni property.
     *
     * @param value allowed object is
     *              {@link TDatum }
     *
     */
    public void setDatumOtevreni(TDatum value) {
        this.datumOtevreni = value;
    }

    /**
     * Gets the value of the datumUzavreni property.
     *
     * @return possible object is
     * {@link TDatum }
     *
     */
    public TDatum getDatumUzavreni() {
        return datumUzavreni;
    }

    /**
     * Sets the value of the datumUzavreni property.
     *
     * @param value allowed object is
     *              {@link TDatum }
     *
     */
    public void setDatumUzavreni(TDatum value) {
        this.datumUzavreni = value;
    }

}
