//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro mateřské entity dílu.
 * 
 * <p>Java class for tMaterskaEntitaDilu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMaterskaEntitaDilu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Soucast" type="{http://www.mvcr.cz/nsesss/v2}tSoucast"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMaterskaEntitaDilu", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "soucast"
})
public class TMaterskaEntitaDilu {

    @XmlElement(name = "Soucast", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TSoucast soucast;

    /**
     * Gets the value of the soucast property.
     * 
     * @return
     *     possible object is
     *     {@link TSoucast }
     *     
     */
    public TSoucast getSoucast() {
        return soucast;
    }

    /**
     * Sets the value of the soucast property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSoucast }
     *     
     */
    public void setSoucast(TSoucast value) {
        this.soucast = value;
    }

}
