//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro mateřské entity součásti.
 *
 * <p>Java class for tMaterskaEntitaSoucasti complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tMaterskaEntitaSoucasti">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TypovySpis" type="{http://www.mvcr.cz/nsesss/v2}tTypovySpis"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMaterskaEntitaSoucasti", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "typovySpis"
})
public class TMaterskaEntitaSoucasti {

    @XmlElement(name = "TypovySpis", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TTypovySpis typovySpis;

    /**
     * Gets the value of the typovySpis property.
     *
     * @return possible object is
     * {@link TTypovySpis }
     *
     */
    public TTypovySpis getTypovySpis() {
        return typovySpis;
    }

    /**
     * Sets the value of the typovySpis property.
     *
     * @param value allowed object is
     *              {@link TTypovySpis }
     *
     */
    public void setTypovySpis(TTypovySpis value) {
        this.typovySpis = value;
    }

}
