//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro možné zaznamenání několika externích subjektů současně.
 * 
 * <p>Java class for tOsobyExterni complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOsobyExterni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Subjekt" type="{http://www.mvcr.cz/nsesss/v2}tSubjektExterni" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOsobyExterni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "subjekt"
})
public class TOsobyExterni {

    @XmlElement(name = "Subjekt", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected List<TSubjektExterni> subjekt;

    /**
     * Gets the value of the subjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSubjektExterni }
     * 
     * 
     */
    public List<TSubjektExterni> getSubjekt() {
        if (subjekt == null) {
            subjekt = new ArrayList<TSubjektExterni>();
        }
        return this.subjekt;
    }

}
