//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro zaznamenání právě jednoho externího subjektu.
 * 
 * <p>Java class for tOsobaExterni complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOsobaExterni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Subjekt" type="{http://www.mvcr.cz/nsesss/v2}tSubjektExterni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOsobaExterni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "subjekt"
})
public class TOsobaExterni {

    @XmlElement(name = "Subjekt", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TSubjektExterni subjekt;

    /**
     * Gets the value of the subjekt property.
     * 
     * @return
     *     possible object is
     *     {@link TSubjektExterni }
     *     
     */
    public TSubjektExterni getSubjekt() {
        return subjekt;
    }

    /**
     * Sets the value of the subjekt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSubjektExterni }
     *     
     */
    public void setSubjekt(TSubjektExterni value) {
        this.subjekt = value;
    }

}
