//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro zaznamenání právě jednoho interního subjektu.
 *
 * <p>Java class for tOsobaInterni complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tOsobaInterni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Subjekt" type="{http://www.mvcr.cz/nsesss/v2}tSubjektInterni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOsobaInterni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "subjekt"
})
public class TOsobaInterni {

    @XmlElement(name = "Subjekt", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TSubjektInterni subjekt;

    /**
     * Gets the value of the subjekt property.
     *
     * @return possible object is
     * {@link TSubjektInterni }
     *
     */
    public TSubjektInterni getSubjekt() {
        return subjekt;
    }

    /**
     * Sets the value of the subjekt property.
     *
     * @param value allowed object is
     *              {@link TSubjektInterni }
     *
     */
    public void setSubjekt(TSubjektInterni value) {
        this.subjekt = value;
    }

}
