//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOvereniBezpecnostnihoPrvku complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tOvereniBezpecnostnihoPrvku">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Certifikat" type="{http://www.mvcr.cz/nsesss/v2}tCertifikat"/>
 *         &lt;element name="OvereniCertifikatu" type="{http://www.mvcr.cz/nsesss/v2}tOvereniCertifikatu"/>
 *         &lt;element name="CasPouziti" type="{http://www.mvcr.cz/nsesss/v2}tDatum" minOccurs="0"/>
 *         &lt;element name="CasOvereni" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="PlatnostBezpecnostnihoPrvku" type="{http://www.mvcr.cz/nsesss/v2}tVysledekOvereni"/>
 *         &lt;element name="Overovatel" type="{http://www.mvcr.cz/nsesss/v2}tOsobaInterni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOvereniBezpecnostnihoPrvku", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "certifikat",
        "overeniCertifikatu",
        "casPouziti",
        "casOvereni",
        "platnostBezpecnostnihoPrvku",
        "overovatel"
})
public class TOvereniBezpecnostnihoPrvku {

    @XmlElement(name = "Certifikat", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TCertifikat certifikat;
    @XmlElement(name = "OvereniCertifikatu", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOvereniCertifikatu overeniCertifikatu;
    @XmlElement(name = "CasPouziti", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TDatum casPouziti;
    @XmlElement(name = "CasOvereni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum casOvereni;
    @XmlElement(name = "PlatnostBezpecnostnihoPrvku", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TVysledekOvereni platnostBezpecnostnihoPrvku;
    @XmlElement(name = "Overovatel", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOsobaInterni overovatel;

    /**
     * Gets the value of the certifikat property.
     *
     * @return possible object is
     * {@link TCertifikat }
     *
     */
    public TCertifikat getCertifikat() {
        return certifikat;
    }

    /**
     * Sets the value of the certifikat property.
     *
     * @param value allowed object is
     *              {@link TCertifikat }
     *
     */
    public void setCertifikat(TCertifikat value) {
        this.certifikat = value;
    }

    /**
     * Gets the value of the overeniCertifikatu property.
     *
     * @return possible object is
     * {@link TOvereniCertifikatu }
     *
     */
    public TOvereniCertifikatu getOvereniCertifikatu() {
        return overeniCertifikatu;
    }

    /**
     * Sets the value of the overeniCertifikatu property.
     *
     * @param value allowed object is
     *              {@link TOvereniCertifikatu }
     *
     */
    public void setOvereniCertifikatu(TOvereniCertifikatu value) {
        this.overeniCertifikatu = value;
    }

    /**
     * Gets the value of the casPouziti property.
     *
     * @return possible object is
     * {@link TDatum }
     *
     */
    public TDatum getCasPouziti() {
        return casPouziti;
    }

    /**
     * Sets the value of the casPouziti property.
     *
     * @param value allowed object is
     *              {@link TDatum }
     *
     */
    public void setCasPouziti(TDatum value) {
        this.casPouziti = value;
    }

    /**
     * Gets the value of the casOvereni property.
     *
     * @return possible object is
     * {@link TDatum }
     *
     */
    public TDatum getCasOvereni() {
        return casOvereni;
    }

    /**
     * Sets the value of the casOvereni property.
     *
     * @param value allowed object is
     *              {@link TDatum }
     *
     */
    public void setCasOvereni(TDatum value) {
        this.casOvereni = value;
    }

    /**
     * Gets the value of the platnostBezpecnostnihoPrvku property.
     *
     * @return possible object is
     * {@link TVysledekOvereni }
     *
     */
    public TVysledekOvereni getPlatnostBezpecnostnihoPrvku() {
        return platnostBezpecnostnihoPrvku;
    }

    /**
     * Sets the value of the platnostBezpecnostnihoPrvku property.
     *
     * @param value allowed object is
     *              {@link TVysledekOvereni }
     *
     */
    public void setPlatnostBezpecnostnihoPrvku(TVysledekOvereni value) {
        this.platnostBezpecnostnihoPrvku = value;
    }

    /**
     * Gets the value of the overovatel property.
     *
     * @return possible object is
     * {@link TOsobaInterni }
     *
     */
    public TOsobaInterni getOverovatel() {
        return overovatel;
    }

    /**
     * Sets the value of the overovatel property.
     *
     * @param value allowed object is
     *              {@link TOsobaInterni }
     *
     */
    public void setOverovatel(TOsobaInterni value) {
        this.overovatel = value;
    }

}
