//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro věcný popis komponenty.
 * 
 * <p>Java class for tPopisKomponenty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPopisKomponenty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nazev" type="{http://www.mvcr.cz/nsesss/v2}tNazev"/>
 *         &lt;element name="Komentar" type="{http://www.mvcr.cz/nsesss/v2}tKomentar" minOccurs="0"/>
 *         &lt;element name="Verze" type="{http://www.mvcr.cz/nsesss/v2}tVerze" minOccurs="0"/>
 *         &lt;element name="KlicovaSlova" type="{http://www.mvcr.cz/nsesss/v2}tKlicovaSlova" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPopisKomponenty", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "nazev",
    "komentar",
    "verze",
    "klicovaSlova"
})
public class TPopisKomponenty {

    @XmlElement(name = "Nazev", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String nazev;
    @XmlElement(name = "Komentar", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String komentar;
    @XmlElement(name = "Verze", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String verze;
    @XmlElement(name = "KlicovaSlova", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TKlicovaSlova klicovaSlova;

    /**
     * Gets the value of the nazev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazev() {
        return nazev;
    }

    /**
     * Sets the value of the nazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazev(String value) {
        this.nazev = value;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomentar(String value) {
        this.komentar = value;
    }

    /**
     * Gets the value of the verze property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerze() {
        return verze;
    }

    /**
     * Sets the value of the verze property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerze(String value) {
        this.verze = value;
    }

    /**
     * Gets the value of the klicovaSlova property.
     * 
     * @return
     *     possible object is
     *     {@link TKlicovaSlova }
     *     
     */
    public TKlicovaSlova getKlicovaSlova() {
        return klicovaSlova;
    }

    /**
     * Sets the value of the klicovaSlova property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKlicovaSlova }
     *     
     */
    public void setKlicovaSlova(TKlicovaSlova value) {
        this.klicovaSlova = value;
    }

}
