//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro popis pravidel určujících podmínky přístupu k entitě.
 * 
 * <p>Java class for tPristupnost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPristupnost">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BezpecnostniKategorie" type="{http://www.mvcr.cz/nsesss/v2}tBezpecnostniKategorie" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="JineOmezeni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPristupnost", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "bezpecnostniKategorie",
    "jineOmezeni"
})
public class TPristupnost {

    @XmlElement(name = "BezpecnostniKategorie", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected List<TBezpecnostniKategorie> bezpecnostniKategorie;
    @XmlElement(name = "JineOmezeni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String jineOmezeni;

    /**
     * Gets the value of the bezpecnostniKategorie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bezpecnostniKategorie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBezpecnostniKategorie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TBezpecnostniKategorie }
     * 
     * 
     */
    public List<TBezpecnostniKategorie> getBezpecnostniKategorie() {
        if (bezpecnostniKategorie == null) {
            bezpecnostniKategorie = new ArrayList<TBezpecnostniKategorie>();
        }
        return this.bezpecnostniKategorie;
    }

    /**
     * Gets the value of the jineOmezeni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJineOmezeni() {
        return jineOmezeni;
    }

    /**
     * Sets the value of the jineOmezeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJineOmezeni(String value) {
        this.jineOmezeni = value;
    }

}
