//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro zaznamenání vzniku entit.
 *
 * <p>Java class for tPuvodSeskupeni complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tPuvodSeskupeni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatumVytvoreni" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPuvodSeskupeni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "datumVytvoreni"
})
public class TPuvodSeskupeni {

    @XmlElement(name = "DatumVytvoreni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum datumVytvoreni;

    /**
     * Gets the value of the datumVytvoreni property.
     *
     * @return possible object is
     * {@link TDatum }
     *
     */
    public TDatum getDatumVytvoreni() {
        return datumVytvoreni;
    }

    /**
     * Sets the value of the datumVytvoreni property.
     *
     * @param value allowed object is
     *              {@link TDatum }
     *
     */
    public void setDatumVytvoreni(TDatum value) {
        this.datumVytvoreni = value;
    }

}
