//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro popis úpravy kopie dokumentu, která zahrnuje proces skrytí určitých informací v dokumentu, jež nejsou potřebné pro další využití kopie dokumentu. Výsledkem procesu redakce je vytvoření výtahu (upravené kopie dokumentu).
 * 
 * <p>Java class for tRedakce complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tRedakce">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Vytah" type="{http://www.mvcr.cz/nsesss/v2}tVytah" maxOccurs="unbounded"/>
 *         &lt;sequence>
 *           &lt;element name="Oduvodneni" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="OdkazPuvodniDokument" type="{http://www.mvcr.cz/nsesss/v2}tOdkaz"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRedakce", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "vytah",
    "oduvodneni",
    "odkazPuvodniDokument"
})
public class TRedakce {

    @XmlElement(name = "Vytah", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected List<TVytah> vytah;
    @XmlElement(name = "Oduvodneni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String oduvodneni;
    @XmlElement(name = "OdkazPuvodniDokument", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TOdkaz odkazPuvodniDokument;

    /**
     * Gets the value of the vytah property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vytah property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVytah().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TVytah }
     * 
     * 
     */
    public List<TVytah> getVytah() {
        if (vytah == null) {
            vytah = new ArrayList<TVytah>();
        }
        return this.vytah;
    }

    /**
     * Gets the value of the oduvodneni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOduvodneni() {
        return oduvodneni;
    }

    /**
     * Sets the value of the oduvodneni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOduvodneni(String value) {
        this.oduvodneni = value;
    }

    /**
     * Gets the value of the odkazPuvodniDokument property.
     * 
     * @return
     *     possible object is
     *     {@link TOdkaz }
     *     
     */
    public TOdkaz getOdkazPuvodniDokument() {
        return odkazPuvodniDokument;
    }

    /**
     * Sets the value of the odkazPuvodniDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOdkaz }
     *     
     */
    public void setOdkazPuvodniDokument(TOdkaz value) {
        this.odkazPuvodniDokument = value;
    }

}
