//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro popis náležitostí skartačního řízení. Prvek je povinný jen u základní entity.
 * 
 * <p>Java class for tSkartacniRizeni complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSkartacniRizeni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="Mnozstvi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SkartacniOperace" type="{http://www.mvcr.cz/nsesss/v2}tSkartacniOperace"/>
 *         &lt;element name="Oduvodneni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Posuzovatel" type="{http://www.mvcr.cz/nsesss/v2}tOsobaInterni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSkartacniRizeni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "datum",
    "mnozstvi",
    "skartacniOperace",
    "oduvodneni",
    "posuzovatel"
})
public class TSkartacniRizeni {

    @XmlElement(name = "Datum", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum datum;
    @XmlElement(name = "Mnozstvi", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String mnozstvi;
    @XmlElement(name = "SkartacniOperace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TSkartacniOperace skartacniOperace;
    @XmlElement(name = "Oduvodneni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String oduvodneni;
    @XmlElement(name = "Posuzovatel", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOsobaInterni posuzovatel;

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setDatum(TDatum value) {
        this.datum = value;
    }

    /**
     * Gets the value of the mnozstvi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMnozstvi() {
        return mnozstvi;
    }

    /**
     * Sets the value of the mnozstvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMnozstvi(String value) {
        this.mnozstvi = value;
    }

    /**
     * Gets the value of the skartacniOperace property.
     * 
     * @return
     *     possible object is
     *     {@link TSkartacniOperace }
     *     
     */
    public TSkartacniOperace getSkartacniOperace() {
        return skartacniOperace;
    }

    /**
     * Sets the value of the skartacniOperace property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSkartacniOperace }
     *     
     */
    public void setSkartacniOperace(TSkartacniOperace value) {
        this.skartacniOperace = value;
    }

    /**
     * Gets the value of the oduvodneni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOduvodneni() {
        return oduvodneni;
    }

    /**
     * Sets the value of the oduvodneni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOduvodneni(String value) {
        this.oduvodneni = value;
    }

    /**
     * Gets the value of the posuzovatel property.
     * 
     * @return
     *     possible object is
     *     {@link TOsobaInterni }
     *     
     */
    public TOsobaInterni getPosuzovatel() {
        return posuzovatel;
    }

    /**
     * Sets the value of the posuzovatel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsobaInterni }
     *     
     */
    public void setPosuzovatel(TOsobaInterni value) {
        this.posuzovatel = value;
    }

}
