//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro popis systému vyřazování entit, který určuje datum zahájení plynutí skartační lhůty, vymezuje dobu ukládání entit a určuje typ skartační operace podle skartačního znaku.
 * 
 * <p>Java class for tSkartacniRezim complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSkartacniRezim">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifikator" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator"/>
 *         &lt;element name="Nazev" type="{http://www.mvcr.cz/nsesss/v2}tNazev"/>
 *         &lt;element name="Komentar" type="{http://www.mvcr.cz/nsesss/v2}tKomentar" minOccurs="0"/>
 *         &lt;element name="Oduvodneni" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SkartacniZnak" type="{http://www.mvcr.cz/nsesss/v2}tSkartacniZnak"/>
 *         &lt;element name="SkartacniLhuta" type="{http://www.mvcr.cz/nsesss/v2}tSkartacniLhuta"/>
 *         &lt;element name="SpousteciUdalost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSkartacniRezim", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "identifikator",
    "nazev",
    "komentar",
    "oduvodneni",
    "skartacniZnak",
    "skartacniLhuta",
    "spousteciUdalost"
})
public class TSkartacniRezim {

    @XmlElement(name = "Identifikator", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TIdentifikator identifikator;
    @XmlElement(name = "Nazev", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String nazev;
    @XmlElement(name = "Komentar", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String komentar;
    @XmlElement(name = "Oduvodneni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String oduvodneni;
    @XmlElement(name = "SkartacniZnak", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TSkartacniZnak skartacniZnak;
    @XmlElement(name = "SkartacniLhuta", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected int skartacniLhuta;
    @XmlElement(name = "SpousteciUdalost", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String spousteciUdalost;

    /**
     * Gets the value of the identifikator property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentifikator }
     *     
     */
    public TIdentifikator getIdentifikator() {
        return identifikator;
    }

    /**
     * Sets the value of the identifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentifikator }
     *     
     */
    public void setIdentifikator(TIdentifikator value) {
        this.identifikator = value;
    }

    /**
     * Gets the value of the nazev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazev() {
        return nazev;
    }

    /**
     * Sets the value of the nazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazev(String value) {
        this.nazev = value;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomentar(String value) {
        this.komentar = value;
    }

    /**
     * Gets the value of the oduvodneni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOduvodneni() {
        return oduvodneni;
    }

    /**
     * Sets the value of the oduvodneni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOduvodneni(String value) {
        this.oduvodneni = value;
    }

    /**
     * Gets the value of the skartacniZnak property.
     * 
     * @return
     *     possible object is
     *     {@link TSkartacniZnak }
     *     
     */
    public TSkartacniZnak getSkartacniZnak() {
        return skartacniZnak;
    }

    /**
     * Sets the value of the skartacniZnak property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSkartacniZnak }
     *     
     */
    public void setSkartacniZnak(TSkartacniZnak value) {
        this.skartacniZnak = value;
    }

    /**
     * Gets the value of the skartacniLhuta property.
     * 
     */
    public int getSkartacniLhuta() {
        return skartacniLhuta;
    }

    /**
     * Sets the value of the skartacniLhuta property.
     * 
     */
    public void setSkartacniLhuta(int value) {
        this.skartacniLhuta = value;
    }

    /**
     * Gets the value of the spousteciUdalost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpousteciUdalost() {
        return spousteciUdalost;
    }

    /**
     * Sets the value of the spousteciUdalost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpousteciUdalost(String value) {
        this.spousteciUdalost = value;
    }

}
