//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro identifikaci právnické nebo fyzické osoby a pro uvedení její poštovní adresy (adresy pro doručování) nebo elektronického kontaktu. Tato osoba je identická s organizací, která tato metadata vytváří, nebo je v zaměstnaneckém poměru k této organizaci.
 *
 * <p>Java class for tSubjektInterni complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tSubjektInterni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentifikatorOrganizace" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator"/>
 *         &lt;element name="NazevOrganizace" type="{http://www.mvcr.cz/nsesss/v2}tNazev"/>
 *         &lt;element name="IdentifikatorFyzickeOsoby" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator"/>
 *         &lt;element name="NazevFyzickeOsoby" type="{http://www.mvcr.cz/nsesss/v2}tNazev"/>
 *         &lt;element name="OrganizacniUtvar" type="{http://www.mvcr.cz/nsesss/v2}tText"/>
 *         &lt;element name="PracovniPozice" type="{http://www.mvcr.cz/nsesss/v2}tText"/>
 *         &lt;element name="SidloOrganizace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSubjektInterni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "identifikatorOrganizace",
        "nazevOrganizace",
        "identifikatorFyzickeOsoby",
        "nazevFyzickeOsoby",
        "organizacniUtvar",
        "pracovniPozice",
        "sidloOrganizace"
})
public class TSubjektInterni {

    @XmlElement(name = "IdentifikatorOrganizace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TIdentifikator identifikatorOrganizace;
    @XmlElement(name = "NazevOrganizace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String nazevOrganizace;
    @XmlElement(name = "IdentifikatorFyzickeOsoby", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TIdentifikator identifikatorFyzickeOsoby;
    @XmlElement(name = "NazevFyzickeOsoby", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String nazevFyzickeOsoby;
    @XmlElement(name = "OrganizacniUtvar", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String organizacniUtvar;
    @XmlElement(name = "PracovniPozice", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String pracovniPozice;
    @XmlElement(name = "SidloOrganizace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String sidloOrganizace;

    /**
     * Gets the value of the identifikatorOrganizace property.
     *
     * @return possible object is
     * {@link TIdentifikator }
     *
     */
    public TIdentifikator getIdentifikatorOrganizace() {
        return identifikatorOrganizace;
    }

    /**
     * Sets the value of the identifikatorOrganizace property.
     *
     * @param value allowed object is
     *              {@link TIdentifikator }
     *
     */
    public void setIdentifikatorOrganizace(TIdentifikator value) {
        this.identifikatorOrganizace = value;
    }

    /**
     * Gets the value of the nazevOrganizace property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getNazevOrganizace() {
        return nazevOrganizace;
    }

    /**
     * Sets the value of the nazevOrganizace property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setNazevOrganizace(String value) {
        this.nazevOrganizace = value;
    }

    /**
     * Gets the value of the identifikatorFyzickeOsoby property.
     *
     * @return possible object is
     * {@link TIdentifikator }
     *
     */
    public TIdentifikator getIdentifikatorFyzickeOsoby() {
        return identifikatorFyzickeOsoby;
    }

    /**
     * Sets the value of the identifikatorFyzickeOsoby property.
     *
     * @param value allowed object is
     *              {@link TIdentifikator }
     *
     */
    public void setIdentifikatorFyzickeOsoby(TIdentifikator value) {
        this.identifikatorFyzickeOsoby = value;
    }

    /**
     * Gets the value of the nazevFyzickeOsoby property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getNazevFyzickeOsoby() {
        return nazevFyzickeOsoby;
    }

    /**
     * Sets the value of the nazevFyzickeOsoby property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setNazevFyzickeOsoby(String value) {
        this.nazevFyzickeOsoby = value;
    }

    /**
     * Gets the value of the organizacniUtvar property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getOrganizacniUtvar() {
        return organizacniUtvar;
    }

    /**
     * Sets the value of the organizacniUtvar property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setOrganizacniUtvar(String value) {
        this.organizacniUtvar = value;
    }

    /**
     * Gets the value of the pracovniPozice property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getPracovniPozice() {
        return pracovniPozice;
    }

    /**
     * Sets the value of the pracovniPozice property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setPracovniPozice(String value) {
        this.pracovniPozice = value;
    }

    /**
     * Gets the value of the sidloOrganizace property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getSidloOrganizace() {
        return sidloOrganizace;
    }

    /**
     * Sets the value of the sidloOrganizace property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setSidloOrganizace(String value) {
        this.sidloOrganizace = value;
    }

}
