//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro zatřídění součásti do hierarchie spisového plánu.
 *
 * <p>Java class for tTrideniSoucasti complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tTrideniSoucasti">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mvcr.cz/nsesss/v2}tTrideni">
 *       &lt;sequence>
 *         &lt;element name="MaterskaEntita" type="{http://www.mvcr.cz/nsesss/v2}tMaterskaEntitaSoucasti"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTrideniSoucasti", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "materskaEntita"
})
public class TTrideniSoucasti
        extends TTrideni {

    @XmlElement(name = "MaterskaEntita", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TMaterskaEntitaSoucasti materskaEntita;

    /**
     * Gets the value of the materskaEntita property.
     *
     * @return possible object is
     * {@link TMaterskaEntitaSoucasti }
     *
     */
    public TMaterskaEntitaSoucasti getMaterskaEntita() {
        return materskaEntita;
    }

    /**
     * Sets the value of the materskaEntita property.
     *
     * @param value allowed object is
     *              {@link TMaterskaEntitaSoucasti }
     *
     */
    public void setMaterskaEntita(TMaterskaEntitaSoucasti value) {
        this.materskaEntita = value;
    }

}
