//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Časový údaj o počátku a konci evidenčního období, ve kterém se spisům nebo dokumentům přidělují jedinečná pořadová čísla v rámci evidence dokumentů. Definice určeného časového období je variabilní a nejčastěji zahrnuje kalendářní rok.
 *
 * <p>Java class for tUrceneCasoveObdobi complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tUrceneCasoveObdobi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="DatumOd" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *           &lt;element name="DatumDo" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="MesicOd" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
 *           &lt;element name="MesicDo" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="RokOd" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *           &lt;element name="RokDo" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="Rok" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tUrceneCasoveObdobi", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "datumOd",
        "datumDo",
        "mesicOd",
        "mesicDo",
        "rokOd",
        "rokDo",
        "rok"
})
public class TUrceneCasoveObdobi {

    @XmlElement(name = "DatumOd", namespace = "http://www.mvcr.cz/nsesss/v2")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumOd;
    @XmlElement(name = "DatumDo", namespace = "http://www.mvcr.cz/nsesss/v2")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDo;
    @XmlElement(name = "MesicOd", namespace = "http://www.mvcr.cz/nsesss/v2")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar mesicOd;
    @XmlElement(name = "MesicDo", namespace = "http://www.mvcr.cz/nsesss/v2")
    @XmlSchemaType(name = "gYearMonth")
    protected XMLGregorianCalendar mesicDo;
    @XmlElement(name = "RokOd", namespace = "http://www.mvcr.cz/nsesss/v2")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar rokOd;
    @XmlElement(name = "RokDo", namespace = "http://www.mvcr.cz/nsesss/v2")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar rokDo;
    @XmlElement(name = "Rok", namespace = "http://www.mvcr.cz/nsesss/v2")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar rok;

    /**
     * Gets the value of the datumOd property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatumOd() {
        return datumOd;
    }

    /**
     * Sets the value of the datumOd property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setDatumOd(XMLGregorianCalendar value) {
        this.datumOd = value;
    }

    /**
     * Gets the value of the datumDo property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatumDo() {
        return datumDo;
    }

    /**
     * Sets the value of the datumDo property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setDatumDo(XMLGregorianCalendar value) {
        this.datumDo = value;
    }

    /**
     * Gets the value of the mesicOd property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getMesicOd() {
        return mesicOd;
    }

    /**
     * Sets the value of the mesicOd property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setMesicOd(XMLGregorianCalendar value) {
        this.mesicOd = value;
    }

    /**
     * Gets the value of the mesicDo property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getMesicDo() {
        return mesicDo;
    }

    /**
     * Sets the value of the mesicDo property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setMesicDo(XMLGregorianCalendar value) {
        this.mesicDo = value;
    }

    /**
     * Gets the value of the rokOd property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getRokOd() {
        return rokOd;
    }

    /**
     * Sets the value of the rokOd property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setRokOd(XMLGregorianCalendar value) {
        this.rokOd = value;
    }

    /**
     * Gets the value of the rokDo property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getRokDo() {
        return rokDo;
    }

    /**
     * Sets the value of the rokDo property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setRokDo(XMLGregorianCalendar value) {
        this.rokDo = value;
    }

    /**
     * Gets the value of the rok property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getRok() {
        return rok;
    }

    /**
     * Sets the value of the rok property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     *
     */
    public void setRok(XMLGregorianCalendar value) {
        this.rok = value;
    }

}
