//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro evidenci údajů o uzavření typového spisu, součásti nebo dílu.
 * 
 * <p>Java class for tUzavreni complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tUzavreni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="Zpracovatel" type="{http://www.mvcr.cz/nsesss/v2}tOsobyInterni"/>
 *         &lt;element name="Konzultant" type="{http://www.mvcr.cz/nsesss/v2}tOsobyInterni" minOccurs="0"/>
 *         &lt;element name="Schvalovani" type="{http://www.mvcr.cz/nsesss/v2}tSchvalovani" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tUzavreni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "datum",
    "zpracovatel",
    "konzultant",
    "schvalovani"
})
public class TUzavreni {

    @XmlElement(name = "Datum", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum datum;
    @XmlElement(name = "Zpracovatel", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOsobyInterni zpracovatel;
    @XmlElement(name = "Konzultant", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TOsobyInterni konzultant;
    @XmlElement(name = "Schvalovani", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TSchvalovani schvalovani;

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setDatum(TDatum value) {
        this.datum = value;
    }

    /**
     * Gets the value of the zpracovatel property.
     * 
     * @return
     *     possible object is
     *     {@link TOsobyInterni }
     *     
     */
    public TOsobyInterni getZpracovatel() {
        return zpracovatel;
    }

    /**
     * Sets the value of the zpracovatel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsobyInterni }
     *     
     */
    public void setZpracovatel(TOsobyInterni value) {
        this.zpracovatel = value;
    }

    /**
     * Gets the value of the konzultant property.
     * 
     * @return
     *     possible object is
     *     {@link TOsobyInterni }
     *     
     */
    public TOsobyInterni getKonzultant() {
        return konzultant;
    }

    /**
     * Sets the value of the konzultant property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsobyInterni }
     *     
     */
    public void setKonzultant(TOsobyInterni value) {
        this.konzultant = value;
    }

    /**
     * Gets the value of the schvalovani property.
     * 
     * @return
     *     possible object is
     *     {@link TSchvalovani }
     *     
     */
    public TSchvalovani getSchvalovani() {
        return schvalovani;
    }

    /**
     * Sets the value of the schvalovani property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSchvalovani }
     *     
     */
    public void setSchvalovani(TSchvalovani value) {
        this.schvalovani = value;
    }

}
