//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro evidenci údajů o skartačním režimu entit, časovém rozsahu plynutí skartační lhůty a náležitostech skartačního řízení.
 *
 * <p>Java class for tVyrazovani complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tVyrazovani">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SkartacniRezim" type="{http://www.mvcr.cz/nsesss/v2}tSkartacniRezim"/>
 *         &lt;element name="DataceVyrazeni" type="{http://www.mvcr.cz/nsesss/v2}tDataceVyrazeni"/>
 *         &lt;element name="SkartacniRizeni" type="{http://www.mvcr.cz/nsesss/v2}tSkartacniRizeni" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tVyrazovani", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "skartacniRezim",
        "dataceVyrazeni",
        "skartacniRizeni"
})
public class TVyrazovani {

    @XmlElement(name = "SkartacniRezim", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TSkartacniRezim skartacniRezim;
    @XmlElement(name = "DataceVyrazeni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDataceVyrazeni dataceVyrazeni;
    @XmlElement(name = "SkartacniRizeni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TSkartacniRizeni skartacniRizeni;

    /**
     * Gets the value of the skartacniRezim property.
     *
     * @return possible object is
     * {@link TSkartacniRezim }
     *
     */
    public TSkartacniRezim getSkartacniRezim() {
        return skartacniRezim;
    }

    /**
     * Sets the value of the skartacniRezim property.
     *
     * @param value allowed object is
     *              {@link TSkartacniRezim }
     *
     */
    public void setSkartacniRezim(TSkartacniRezim value) {
        this.skartacniRezim = value;
    }

    /**
     * Gets the value of the dataceVyrazeni property.
     *
     * @return possible object is
     * {@link TDataceVyrazeni }
     *
     */
    public TDataceVyrazeni getDataceVyrazeni() {
        return dataceVyrazeni;
    }

    /**
     * Sets the value of the dataceVyrazeni property.
     *
     * @param value allowed object is
     *              {@link TDataceVyrazeni }
     *
     */
    public void setDataceVyrazeni(TDataceVyrazeni value) {
        this.dataceVyrazeni = value;
    }

    /**
     * Gets the value of the skartacniRizeni property.
     *
     * @return possible object is
     * {@link TSkartacniRizeni }
     *
     */
    public TSkartacniRizeni getSkartacniRizeni() {
        return skartacniRizeni;
    }

    /**
     * Sets the value of the skartacniRizeni property.
     *
     * @param value allowed object is
     *              {@link TSkartacniRizeni }
     *
     */
    public void setSkartacniRizeni(TSkartacniRizeni value) {
        this.skartacniRizeni = value;
    }

}
