//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro evidenci údajů o vyřízení a uzavření entity a případném odeslání vyřizujícího dokumentu.
 *
 * <p>Java class for tVyrizeniEntity complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tVyrizeniEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mvcr.cz/nsesss/v2}tVyrizeni">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="2" minOccurs="0">
 *           &lt;element name="OdkazVyrizujiciDokument" type="{http://www.mvcr.cz/nsesss/v2}tOdkaz"/>
 *           &lt;element name="OdkazVyrizovanyDokument" type="{http://www.mvcr.cz/nsesss/v2}tOdkaz"/>
 *         &lt;/choice>
 *         &lt;element name="DatumOdeslani" type="{http://www.mvcr.cz/nsesss/v2}tDatum" minOccurs="0"/>
 *         &lt;element name="OdeslaneMnozstvi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Prijemce" type="{http://www.mvcr.cz/nsesss/v2}tOsobyExterni" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tVyrizeniEntity", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "odkazVyrizujiciDokumentOrOdkazVyrizovanyDokument",
        "datumOdeslani",
        "odeslaneMnozstvi",
        "prijemce"
})
public class TVyrizeniEntity
        extends TVyrizeni {

    @XmlElementRefs({
            @XmlElementRef(name = "OdkazVyrizovanyDokument", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
            @XmlElementRef(name = "OdkazVyrizujiciDokument", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class)
    })
    protected List<JAXBElement<TOdkaz>> odkazVyrizujiciDokumentOrOdkazVyrizovanyDokument;
    @XmlElement(name = "DatumOdeslani", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TDatum datumOdeslani;
    @XmlElement(name = "OdeslaneMnozstvi", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String odeslaneMnozstvi;
    @XmlElement(name = "Prijemce", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TOsobyExterni prijemce;

    /**
     * Gets the value of the odkazVyrizujiciDokumentOrOdkazVyrizovanyDokument property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the odkazVyrizujiciDokumentOrOdkazVyrizovanyDokument property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOdkazVyrizujiciDokumentOrOdkazVyrizovanyDokument().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TOdkaz }{@code >}
     * {@link JAXBElement }{@code <}{@link TOdkaz }{@code >}
     *
     *
     */
    public List<JAXBElement<TOdkaz>> getOdkazVyrizujiciDokumentOrOdkazVyrizovanyDokument() {
        if (odkazVyrizujiciDokumentOrOdkazVyrizovanyDokument == null) {
            odkazVyrizujiciDokumentOrOdkazVyrizovanyDokument = new ArrayList<JAXBElement<TOdkaz>>();
        }
        return this.odkazVyrizujiciDokumentOrOdkazVyrizovanyDokument;
    }

    /**
     * Gets the value of the datumOdeslani property.
     *
     * @return possible object is
     * {@link TDatum }
     *
     */
    public TDatum getDatumOdeslani() {
        return datumOdeslani;
    }

    /**
     * Sets the value of the datumOdeslani property.
     *
     * @param value allowed object is
     *              {@link TDatum }
     *
     */
    public void setDatumOdeslani(TDatum value) {
        this.datumOdeslani = value;
    }

    /**
     * Gets the value of the odeslaneMnozstvi property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getOdeslaneMnozstvi() {
        return odeslaneMnozstvi;
    }

    /**
     * Sets the value of the odeslaneMnozstvi property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setOdeslaneMnozstvi(String value) {
        this.odeslaneMnozstvi = value;
    }

    /**
     * Gets the value of the prijemce property.
     *
     * @return possible object is
     * {@link TOsobyExterni }
     *
     */
    public TOsobyExterni getPrijemce() {
        return prijemce;
    }

    /**
     * Sets the value of the prijemce property.
     *
     * @param value allowed object is
     *              {@link TOsobyExterni }
     *
     */
    public void setPrijemce(TOsobyExterni value) {
        this.prijemce = value;
    }

}
