//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro identifikaci výstupní entity (dokumentu nebo komponenty) vzešlé z procesu konverze.
 *
 * <p>Java class for tVystup complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="tVystup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Oduvodneni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OdkazVystup" type="{http://www.mvcr.cz/nsesss/v2}tOdkaz"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tVystup", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
        "oduvodneni",
        "odkazVystup"
})
public class TVystup {

    @XmlElement(name = "Oduvodneni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String oduvodneni;
    @XmlElement(name = "OdkazVystup", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOdkaz odkazVystup;

    /**
     * Gets the value of the oduvodneni property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getOduvodneni() {
        return oduvodneni;
    }

    /**
     * Sets the value of the oduvodneni property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setOduvodneni(String value) {
        this.oduvodneni = value;
    }

    /**
     * Gets the value of the odkazVystup property.
     *
     * @return possible object is
     * {@link TOdkaz }
     *
     */
    public TOdkaz getOdkazVystup() {
        return odkazVystup;
    }

    /**
     * Sets the value of the odkazVystup property.
     *
     * @param value allowed object is
     *              {@link TOdkaz }
     *
     */
    public void setOdkazVystup(TOdkaz value) {
        this.odkazVystup = value;
    }

}
