//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.nsesss2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tZpusobVyrizeni.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tZpusobVyrizeni">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="vyřízení dokumentem"/>
 *     &lt;enumeration value="postoupení"/>
 *     &lt;enumeration value="vzetí na vědomí"/>
 *     &lt;enumeration value="jiný způsob"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tZpusobVyrizeni", namespace = "http://www.mvcr.cz/nsesss/v2")
@XmlEnum
public enum TZpusobVyrizeni {

    @XmlEnumValue("vy\u0159\u00edzen\u00ed dokumentem")
    VYŘÍZENÍ_DOKUMENTEM("vy\u0159\u00edzen\u00ed dokumentem"),
    @XmlEnumValue("postoupen\u00ed")
    POSTOUPENÍ("postoupen\u00ed"),
    @XmlEnumValue("vzet\u00ed na v\u011bdom\u00ed")
    VZETÍ_NA_VĚDOMÍ("vzet\u00ed na v\u011bdom\u00ed"),
    @XmlEnumValue("jin\u00fd zp\u016fsob")
    JINÝ_ZPŮSOB("jin\u00fd zp\u016fsob");
    private final String value;

    TZpusobVyrizeni(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TZpusobVyrizeni fromValue(String v) {
        for (TZpusobVyrizeni c: TZpusobVyrizeni.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
