<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output indent="yes" method="xml" version="1.0" encoding="UTF-8"/>

	<xsl:template name="iso-639-2b-converter">
        <xsl:param name="languageCode"/>
        <xsl:variable name="lowerCaseLanguageCode" select="translate(
            $languageCode,
            'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
            'abcdefghijklmnopqrstuvwxyz'  )"/>

        <xsl:variable name="resultCode">
            <xsl:choose>
                <xsl:when test="string-length($lowerCaseLanguageCode) = 2">
                    <xsl:value-of select="$lowerCaseLanguageCode"/>
                </xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'abk'">ab</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'aar'">aa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'afr'">af</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'aka'">ak</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'alb'">sq</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'amh'">am</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ara'">ar</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'arg'">an</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'arm'">hy</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'asm'">as</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ava'">av</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ave'">ae</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'aym'">ay</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'aze'">az</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bam'">bm</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bak'">ba</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'baq'">eu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bel'">be</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ben'">bn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bih'">bh</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bis'">bi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bos'">bs</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bre'">br</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bul'">bg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bur'">my</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cat'">ca</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cha'">ch</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'che'">ce</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nya'">ny</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'chi'">zh</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'chv'">cv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cor'">kw</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cos'">co</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cre'">cr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hrv'">hr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cze'">cs</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'dan'">da</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'div'">dv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'dut'">nl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'dzo'">dz</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'eng'">en</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'epo'">eo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'est'">et</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ewe'">ee</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fao'">fo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fij'">fj</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fin'">fi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fre'">fr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ful'">ff</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'glg'">gl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'geo'">ka</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ger'">de</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'gre'">el</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'grn'">gn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'guj'">gu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hat'">ht</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hau'">ha</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'heb'">he</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'her'">hz</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hin'">hi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hmo'">ho</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hun'">hu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ina'">ia</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ind'">id</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ile'">ie</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'gle'">ga</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ibo'">ig</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ipk'">ik</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ido'">io</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ice'">is</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ita'">it</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'iku'">iu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'jpn'">ja</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'jav'">jv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kal'">kl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kan'">kn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kau'">kr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kas'">ks</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kaz'">kk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'khm'">km</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kik'">ki</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kin'">rw</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kir'">ky</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kom'">kv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kon'">kg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kor'">ko</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kur'">ku</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kua'">kj</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lat'">la</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ltz'">lb</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lug'">lg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lim'">li</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lin'">ln</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lao'">lo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lit'">lt</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lub'">lu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lav'">lv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'glv'">gv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mac'">mk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mlg'">mg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'may'">ms</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mal'">ml</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mlt'">mt</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mao'">mi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mar'">mr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mah'">mh</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mon'">mn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nau'">na</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nav'">nv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nob'">nb</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nde'">nd</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nep'">ne</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ndo'">ng</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nno'">nn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nor'">no</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'iii'">ii</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nbl'">nr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'oci'">oc</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'oji'">oj</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'chu'">cu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'orm'">om</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ori'">or</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'oss'">os</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'pan'">pa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'pli'">pi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'per'">fa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'pol'">pl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'pus'">ps</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'por'">pt</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'que'">qu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'roh'">rm</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'run'">rn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'rum'">ro</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'rus'">ru</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'san'">sa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'srd'">sc</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'snd'">sd</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sme'">se</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'smo'">sm</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sag'">sg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'srp'">sr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'gla'">gd</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sna'">sn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sin'">si</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'slo'">sk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'slv'">sl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'som'">so</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sot'">st</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'spa'">es</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sun'">su</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'swa'">sw</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ssw'">ss</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'swe'">sv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tam'">ta</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tel'">te</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tgk'">tg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tha'">th</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tir'">ti</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tib'">bo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tuk'">tk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tgl'">tl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tsn'">tn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ton'">to</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tur'">tr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tso'">ts</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tat'">tt</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'twi'">tw</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tah'">ty</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'uig'">ug</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ukr'">uk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'urd'">ur</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'uzb'">uz</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ven'">ve</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'vie'">vi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'vol'">vo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'wln'">wa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'wel'">cy</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'wol'">wo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fry'">fy</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'xho'">xh</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'yid'">yi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'yor'">yo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'zha'">za</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'zul'">zu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'abk'">ab</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'aar'">aa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'afr'">af</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'aka'">ak</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'alb'">sq</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'amh'">am</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ara'">ar</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'arg'">an</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'arm'">hy</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'asm'">as</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ava'">av</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ave'">ae</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'aym'">ay</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'aze'">az</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bam'">bm</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bak'">ba</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'baq'">eu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bel'">be</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ben'">bn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bih'">bh</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bis'">bi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bos'">bs</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bre'">br</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bul'">bg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'bur'">my</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cat'">ca</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cha'">ch</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'che'">ce</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nya'">ny</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'chi'">zh</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'chv'">cv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cor'">kw</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cos'">co</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cre'">cr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hrv'">hr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'cze'">cs</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'dan'">da</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'div'">dv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'dut'">nl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'dzo'">dz</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'eng'">en</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'epo'">eo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'est'">et</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ewe'">ee</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fao'">fo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fij'">fj</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fin'">fi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fre'">fr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ful'">ff</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'glg'">gl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'geo'">ka</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ger'">de</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'gre'">el</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'grn'">gn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'guj'">gu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hat'">ht</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hau'">ha</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'heb'">he</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'her'">hz</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hin'">hi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hmo'">ho</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'hun'">hu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ina'">ia</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ind'">id</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ile'">ie</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'gle'">ga</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ibo'">ig</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ipk'">ik</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ido'">io</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ice'">is</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ita'">it</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'iku'">iu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'jpn'">ja</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'jav'">jv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kal'">kl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kan'">kn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kau'">kr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kas'">ks</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kaz'">kk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'khm'">km</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kik'">ki</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kin'">rw</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kir'">ky</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kom'">kv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kon'">kg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kor'">ko</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kur'">ku</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'kua'">kj</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lat'">la</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ltz'">lb</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lug'">lg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lim'">li</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lin'">ln</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lao'">lo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lit'">lt</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lub'">lu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'lav'">lv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'glv'">gv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mac'">mk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mlg'">mg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'may'">ms</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mal'">ml</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mlt'">mt</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mao'">mi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mar'">mr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mah'">mh</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'mon'">mn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nau'">na</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nav'">nv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nob'">nb</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nde'">nd</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nep'">ne</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ndo'">ng</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nno'">nn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nor'">no</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'iii'">ii</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'nbl'">nr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'oci'">oc</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'oji'">oj</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'chu'">cu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'orm'">om</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ori'">or</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'oss'">os</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'pan'">pa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'pli'">pi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'per'">fa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'pol'">pl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'pus'">ps</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'por'">pt</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'que'">qu</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'roh'">rm</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'run'">rn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'rum'">ro</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'rus'">ru</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'san'">sa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'srd'">sc</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'snd'">sd</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sme'">se</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'smo'">sm</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sag'">sg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'srp'">sr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'gla'">gd</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sna'">sn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sin'">si</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'slo'">sk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'slv'">sl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'som'">so</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sot'">st</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'spa'">es</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'sun'">su</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'swa'">sw</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ssw'">ss</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'swe'">sv</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tam'">ta</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tel'">te</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tgk'">tg</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tha'">th</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tir'">ti</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tib'">bo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tuk'">tk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tgl'">tl</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tsn'">tn</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ton'">to</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tur'">tr</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tso'">ts</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tat'">tt</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'twi'">tw</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'tah'">ty</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'uig'">ug</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ukr'">uk</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'urd'">ur</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'uzb'">uz</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'ven'">ve</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'vie'">vi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'vol'">vo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'wln'">wa</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'wel'">cy</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'wol'">wo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'fry'">fy</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'xho'">xh</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'yid'">yi</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'yor'">yo</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'zha'">za</xsl:when>
                <xsl:when test="$lowerCaseLanguageCode = 'zul'">zu</xsl:when>

                <xsl:otherwise>
                    <xsl:value-of select="$lowerCaseLanguageCode"/>
                </xsl:otherwise>
            </xsl:choose>
        </xsl:variable>

        <xsl:if test="$resultCode != ''">
            <xsl:value-of select="$resultCode"/>
        </xsl:if>
    </xsl:template>

</xsl:stylesheet>