### LOGIN
POST http://localhost:8081/proarc/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

###

PUT http://localhost:8081/proarc/rest/v1/object/mods/editorPages
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&isc_metaDataPrefix=_&isc_dataFormat=json&pids=[uuid%3A3bd2ed5e-36f0-44d4-8f21-b7230e71ab61,uuid%3A83f5ac44-3a40-4953-8013-2e1c63e71ad8,uuid%3A59904a07-3f23-4518-ba70-24f16cdf27e4]&timestamp=1597146647990&editorId=model%3Andkpage&_operationType=update&_textMatchStyle=exact&_dataSource=ModsCustomDataSource&sequence=ALPHABET_LOWER_SERIES&applyTo=1&pageType=obituary&prefix=[[&suffix=]a]&startNumber=28&incrementNumber=1&applyTo=2}


###

PUT http://localhost:8081/proarc/rest/v1/object/mods/editorPages
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&isc_metaDataPrefix=_&isc_dataFormat=json&pids=[uuid%3A341dfe44-2ba1-4ac6-a987-c2e49f148dde,uuid%3Af5a48346-c4b3-4e7d-a496-ce7f571d9aa0,uuid%3Af593ee5d-2941-44af-b3c8-8996d4fd87dd,uuid%3A7cef5162-b3ae-4017-9378-6bf80031b84a]&timestamp=1597146647990&editorId=model%3Andkpage&_operationType=update&_textMatchStyle=exact&_dataSource=ModsCustomDataSource&sequence=ALPHABET_LOWER_SERIES&applyTo=2&pageType=titlePage&prefix=[[&suffix=]a]&startNumber=28&incrementNumber=1&applyToFirstPage=true}

###

PUT http://localhost:8081/proarc/rest/v1/object/mods/editorPages
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&pids=[uuid%3Aa17a419d-d847-44f9-8d03-53a86dea6bec,uuid%3A50c5c2a5-7823-4a66-bffd-85c53a85a0ff,uuid%3Af95a1c52-9934-434e-aa19-87b27cafb5b1,uuid%3A58229239-adfc-4fca-87cb-cdb8f953cb76,uuid%3Aeee4fda9-ff2b-4be5-9be5-5d09e41be946]&applyTo=1&startIndex=1}

###

PUT http://localhost:8081/proarc/rest/v1/object/mods/editorPages
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&pids=[uuid%3A0390e277-1ee6-4a39-973b-9a22ae397c07,uuid%3A65538481-8f91-4d75-8371-0ef16b7ffe72,uuid%3A046178de-2faf-42c4-8784-24088ecccb62]&startNumber=28&incrementNumber=1&applyToFirstPage=true&useBrackets=true&doubleColumns=true&sequence=ALPHABET_LOWER_SERIES&pagePosition=right_left}

###

PUT http://localhost:8081/proarc/rest/v1/object/mods/editorPages
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&isc_metaDataPrefix=_&isc_dataFormat=json&pids=[uuid%3A18ab20d4-6c85-480b-8799-24e17639cc08]&_operationType=update&_dataSource=ModsCustomDataSource&sequence=ALPHABET_LOWER_SERIES&applyTo=2&pageType=titlePage&prefix=[&suffix=]&startNumber=28&incrementNumber=1&applyToFirstPage=true&useBrackets=true}

###

PUT http://localhost:8081/proarc/rest/v1/object/mods/editorPages
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&pids=[uuid%3A18ab20d4-6c85-480b-8799-24e17639cc08]&_operationType=update&_dataSource=ModsCustomDataSource&useBrackets=true}

###

PUT http://localhost:8081/proarc/rest/v1/object/mods/editorPages
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&pids=[uuid%3A960da246-e702-4e35-90b5-719d8a4d414d,uuid%3Ac2ead985-fa15-40b7-827b-2cc13b925731,uuid%3A79ed111c-1aec-40ad-82bd-7c7a190b266b]&batchId=453&_operationType=update&_dataSource=ModsCustomDataSource&pageType=titlePage}

###

POST http://localhost:8081/proarc/rest/v1/object/mods/addBrackets
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&pids=[uuid%3A18ab20d4-6c85-480b-8799-24e17639cc08]&_operationType=update&_dataSource=ModsCustomDataSource}

### local

POST http://localhost:8081/proarc/rest/v1/object/mods/addBrackets
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&pids=[uuid%3A960da246-e702-4e35-90b5-719d8a4d414d,uuid%3Ac2ead985-fa15-40b7-827b-2cc13b925731,uuid%3A79ed111c-1aec-40ad-82bd-7c7a190b266b]&batchId=453&_operationType=update&_dataSource=ModsCustomDataSource}

###

POST http://localhost:8081/proarc/rest/v1/object/mods/removeBrackets
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&pids=[uuid%3A18ab20d4-6c85-480b-8799-24e17639cc08]&_operationType=update&_dataSource=ModsCustomDataSource}

### local

POST http://localhost:8081/proarc/rest/v1/object/mods/removeBrackets
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&pids=[uuid%3A960da246-e702-4e35-90b5-719d8a4d414d,uuid%3Ac2ead985-fa15-40b7-827b-2cc13b925731,uuid%3A79ed111c-1aec-40ad-82bd-7c7a190b266b]&batchId=453&_operationType=update&_dataSource=ModsCustomDataSource}

###

POST http://localhost:8081/proarc/rest/v1/import/batches
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&folderPath=[Monografie%2FMetodika2%2F,Periodikum%2Fkrasanasehodomova%2F1%2F]&profile=profile.default&indices=true&device=device%3Ab99a9bbc-1158-48de-84e7-34785fe4eaec&_operationType=add&_textMatchStyle=exact&_dataSource=ImportBatchDataSource&isc_metaDataPrefix=_&isc_dataFormat=json}

###

GET http://localhost:8081/proarc/rest/v1/import/processingBatches
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

###

GET http://localhost:8081/proarc/rest/v1/import/processingBatches?state=INGESTING_FAILED

###

GET http://localhost:8081/proarc/rest/v1/info


###

POST http://localhost:8081/proarc/rest/v1/import/batch/unlockFolder
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&folderPath=Monografie%2FKratkaBezAlto%2F&_textMatchStyle=exact&isc_dataFormat=json}

###

POST http://localhost:8081/proarc/rest/v1/indexer
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

###

GET http://localhost:8081/proarc/rest/v1/object/createPid

### LOGIN
POST http://localhost:8081/proarc/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

###

POST http://localhost:8081/proarc/rest/v2/import/batchStopped
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&id=943&_operationType=add&_textMatchStyle=exact&_dataSource=ImportBatchDataSource&isc_metaDataPrefix=_&isc_dataFormat=json}

###

POST http://localhost:8081/proarc/rest/v1/object/mods/editorPagesCopyMetadata
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&sourcePids=[uuid%3A3bd2ed5e-36f0-44d4-8f21-b7230e71ab61,uuid%3A83f5ac44-3a40-4953-8013-2e1c63e71ad8,uuid%3A59904a07-3f23-4518-ba70-24f16cdf27e4]&destinationPids=[uuid%3A3bd3ed5e-36f0-44d4-8f21-b7230e71ab61,uuid%3A83f53c44-3a40-4953-8013-2e1c63e71ad8,uuid%3A59904a03-3f23-4518-ba70-24f16cdf27e4]&copyPageIndex=true&copyPageNumber=false&copyPageType=true&batchId=12}

###

POST http://localhost:8081/proarc/rest/v1/object/mods/editorPagesCopyMetadata
Content-Type: application/json

{"sourcePids":["uuid:83702174-8d13-496c-b6e7-b435c0ae0a12"],"destinationPids":["uuid:edfbe2b3-5e92-4177-af3d-cdf57fbc9407","uuid:6e6fe60a-3f6d-49c1-8179-e140b2b7e4d0","uuid:249a3e2a-6d41-4fa4-aa53-bcfe545355ce"],"copyPageIndex":true,"copyPageNumber":true,"copyPageType":false,"batchId":"594"}
###

DELETE http://localhost:8081/proarc/rest/v1/object
Content-Type: application/json

{"pid":["uuid:83702174-8d13-496c-b6e7-b435c0ae0a12"],"hierarchy":true, "purge":true, "restore":false}

###

DELETE http://localhost:8081/proarc/rest/v1/import/batch/item
Content-Type: application/json

{"pid":["uuid:83702174-8d13-496c-b6e7-b435c0ae0a12"],"batchId":"135"}

###

POST http://localhost:8081/proarc/rest/v1/object/mods/validate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid%3A696ad6af-b3ab-431d-a4c4-149571ee71eb


###
POST http://localhost:8081/proarc/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username=proarc&j_password=proarcAdmin

<> 2023-01-26T100714.200.html

###
POST http://localhost:8081/proarc/rest/v1/kramerius/edit
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

instance=kramerius7&pid=uuid:27e8598c-59d8-11ed-a227-001b63bd97ba

###
GET http://localhost:8081/proarc/rest/v1/kramerius/viewMods?instance=kramerius7&pid=uuid:27e8598c-59d8-11ed-a227-001b63bd97ba
Accept: application/jsonf
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

###
POST http://localhost:8081/proarc/rest/v1/kramerius/importToProArc
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

instance=kramerius7&pid=uuid:27e8598c-59d8-11ed-a227-001b63bd97ba

###
POST http://localhost:8081/proarc/rest/v1/kramerius/importToKramerius
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

instance=kramerius7&importInstance=kramerius7&pid=uuid:27e8598c-59d8-11ed-a227-001b63bd97ba


### LOGIN
POST {{proarcLocalHostUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### Kramerius export
POST {{proarcLocalHostUrl}}/rest/v2/export/kramerius4
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

pid=uuid%3Ae5031795-e913-4cb4-9d7b-074fdb5d400c&license=onsite&krameriusInstance=local
###
POST {{proarcLocalHostUrl}}/rest/v1/export/reexport
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

id=763

### UPDATE XML
PUT {{proarcLocalHostUrl}}/rest/v1/object/mods/custom
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid%3Aa0c1d3ed-59e9-4b12-8b59-c2ff2690e511&editorId=model:ndkmonographvolume&xmlData=<?xml version="1.0" encoding="UTF-8" standalone="yes"?><mods:mods version="3.6" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink"><mods:genre>volume</mods:genre><mods:identifier type="uuid">a0c1d3ed-59e9-4b12-8b59-c2ff2690e511</mods:identifier><mods:recordInfo><mods:recordCreationDate encoding="iso8601">20230222T112645</mods:recordCreationDate><mods:recordChangeDate encoding="iso8601">20230222T112645</mods:recordChangeDate><mods:descriptionStandard>rda</mods:descriptionStandard></mods:recordInfo><mods:typeOfResource>text</mods:typeOfResource></mods:mods>&timestamp=1677062754083&standard=rda


### GET XML
GET {{proarcLocalHostUrl}}/rest/v1/object/mods/plain?pid=uuid%3Aa0c1d3ed-59e9-4b12-8b59-c2ff2690e511
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8


### NDK Export s Bagit
POST {{proarcNmUrl}}/rest/v1/export/ndk
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{nmUuid}}&isBagit=true

### Archive Export s Bagit
POST {{proarcLocalHostUrl}}/rest/v1/export/archive
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{localUuid}}&isBagit=true


### LOGIN
POST {{proarcLocalHostUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### Archive Export s Bagit
POST {{proarcLocalHostUrl}}/rest/v1/export/archive
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{localUuid}}&isBagit=true

### NDK Export s Bagit
POST {{proarcRemoteUrl}}/rest/v1/export/ndk
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{remoteUuid}}&isBagit=true


### GENERATE ALTO OCR RECURSIVELY
POST {{proarcCroUrl}}/rest/v1/import/generate
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&folderPath=denicky2


### LOGIN
POST {{proarcRemoteUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### GET VALID EXPORTS
GET {{proarcLocalHostUrl}}/rest/v1/export/validExports?model=model:oldprintvolume
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

### ADD NEW USER WOTH ERROR
POST {{proarcLocalHostUrl}}/rest/v1/user
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&name=miqchal


### REINDEX
PUT {{proarcLocalHostUrl}}/rest/v1/object/reindexObjects
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&batchId=845&model=model:ndkpage

### EDITOR PAGES
PUT http://localhost:8081/proarc/rest/v1/object/mods/editorPages
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

{&batchId=830&isc_metaDataPrefix=_&isc_dataFormat=json&pids=[uuid%3A5c52de64-2d85-4a13-a65b-1d0ff6d6650c,uuid%3Af7cf6e41-68e3-4919-be5f-a5548b5a3669]&timestamp=1597146647990&editorId=model%3Andkpage&_operationType=update&_textMatchStyle=exact&_dataSource=ModsCustomDataSource&pageType=obituary}


### LOGIN
POST {{proarcLocalHostUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}


### IMPORT
POST {{proarcRemoteUrl}}/rest/v1/import/batch
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&folderPath=Mzk/Monografie/Kratka/&profile=profile.default&device=device:a93dd5e2-1db7-44d0-be85-804759da8afe&priority=medium

### EXPORT KRAMERIUS
POST {{proarcLocalHostUrl}}/rest/v1/export/archive
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:4a3b4ef7-0bc0-44e6-b0e2-9624d8ebb80e&isBagit=true



###

GET https://ltp.cesnet.cz/api/v2/archive/?group=VO_nm&limit=10
Authorization: Token df5586976a16146e59194708f54908d37cde49ae158f2a4a971be179d3c6faaa
Content-Type: application/json

###

GET https://ltp.cesnet.cz/api/v2/archive/?group=VO_nm&limit=10
Authorization: Token df5586976a16146e59194708f54908d37cde49ae158f2a4a971be179d3c6faaa
Content-Type: application/json


### LOGIN
POST {{proarcLocalHostUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### NDK EXPORT with CESNET UPLOAD
POST {{proarcLocalHostUrl}}/rest/v2/export/ndk
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:4d696c27-9253-41a6-bb24-9c0b6fdde49b&ltpCesnet=true&ltpCesnetToken=0c291bf25d646a50757188da518e74d13322ed48e4fb0cc2bc8df0332f32b0f3
###
POST {{proarcLocalHostUrl}}/rest/v2/object/unlockObject
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:fb3e739d-37a4-4cc0-8fba-4296f99a988d


### LOGIN
POST {{proarcNmUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### NDK EXPORT with CESNET UPLOAD
POST {{proarcNmUrl}}/rest/v2/export/ndk
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:0d8c130c-a170-4ca7-a20b-c4b8870cea5d&ltpCesnet=true&ltpCesnetToken=0c291bf25d646a50757188da518e74d13322ed48e4fb0cc2bc8df0332f32b0f3


select id, "CREATE", state from proarc_batch where folder = 'uuid:ed2ae08a-2333-4acb-80e2-c2722171ac9e';


### LOGIN
POST {{proarcLocalHostUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### Update device
PUT {{proarcLocalHostUrl}}/rest/v2/device
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&device:1883a7de-2f01-40e4-91ee-c7b631c0353c


### NDK Export s Bagit
POST {{proarcLocalHostUrl}}/rest/v1/export/ndk
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{uuid}}&krameriusInstance=kramerius7


### NDK Export s Kramerius Importem
POST {{proarcRemoteUrl}}/rest/v2/export/ndk
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{remoteUuid}}&krameriusInstance=kramerius7

### LOGIN
POST {{proarcRemoteUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### LOGIN
POST {{proarcLocalHostUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### REGISTER URNNBN
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:32c47d0e-25f6-4113-89ab-4ecd23050b3b&resolverId=inovatika

### INVALIDATE LOCAL URNNBN
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/invalidateLocal
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:32c47d0e-25f6-4113-89ab-4ecd23050b3b&resolverId=inovatika

### INVALIDATE REMOTE URNNBN
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/invalidateRemote
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&valueToDeactivate=urn:nbn:cz:aba007-000111&resolverId=inovatika

### NEW REGISTRATION URNNBN WITH OLD VALUE DEACTIVATION
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/registerAgain
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:5d3fba10-2f81-4262-8a24-7c1e38eeba55&resolverId=inovatika

### REGISTER URNNBN - SUCCESSOR
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/createSuccessor
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

#&pid=uuid:32c47d0e-25f6-4113-89ab-4ecd23050b3b&resolcerId=inovatika
&pid=uuid:bab0d255-4819-45f0-9521-28715cabfee1&resolverId=inovatika

### UPDATE RESOLVER WITH IDENTIFIER
POST {{proarcLocalHostUrl}}/rest/v2/object/urnnbn/updateIdentifier
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:5d3fba10-2f81-4262-8a24-7c1e38eeba55&resolverId=inovatika&identifier=ccnb&operation=update

### LOGIN
POST {{proarcLocalHostUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### IMPORT WITH REWRITE WITH NEW
PUT {{proarcLocalHostUrl}}/rest/v2/import/batch
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&state=LOADING_FAILED&profile=profile.ndk_periodical_kramerius_import&id=86&useNewMetadata=true

### LOGIN
POST {{proarcLocalHostUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### UPDATE VERBIS RECORD
POST {{proarcLocalHostUrl}}/rest/v2/object/updateCatalogRecord
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid=uuid:455a7723-c4ab-4b80-8e75-b1203ccefa59&catalogId=cmh


### GET RELEVANT CATALOG

GET {{proarcLocalHostUrl}}/rest/v1/bibliographies?allowUpdate=true
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

### update oldprint page

PUT {{proarcLocalHostUrl}}/rest/v1/object/mods/custom
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

pid=uuid:01c76b77-09bf-438e-8659-1eb910284e3c&editorId=model:oldprintpage&jsonData={"mods":{"identifier":[{"type":"uuid","value":"ac76fd47-abe2-46d7-8029-278806ebec64"}],"note":[{"value":"right"}],"genre":[{"value":"reprePage"}]},"pageNumber":"8","pageIndex":"8","pageType":"normalPage"}&timestamp=1696856079750


### LOGIN
POST {{proarcUrl}}/proarclogin
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&j_username={{proarcUsername}}&j_password={{proarcPwd}}

### CREATE PERIODICAL ISSUE
POST {{proarcLocalHostUrl}}/rest/v2/object
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

seriesPartNumberFrom=61&seriesDateFrom=2022-01-01&seriesDateTo=2022-05-01&model=model%3Andkperiodicalissue&parent=uuid:4f749d4c-7580-4211-b634-c3ec7fea75f0&seriesDateFormat=dd.mm.yyyy&seriesFrequency=w&seriesDaysIncluded=3


### GENERATE ALTO TO PID
POST {{proarcUrl}}/rest/v2/object/generateAlto
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&pid={{uuid}}

### GENERATE ALTO TO FOLDER
POST {{proarcLocalHostUrl}}/rest/v2/import/generateAlto
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

&folderPath=altoToTest