//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EvidencniUdaje" type="{http://www.mvcr.cz/nsesss/v2}tEvidencniUdajeDilu"/>
 *         &lt;element name="Dokumenty" type="{http://www.mvcr.cz/nsesss/v2}tDokumenty" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "evidencniUdaje",
    "dokumenty"
})
@XmlRootElement(name = "Dil", namespace = "http://www.mvcr.cz/nsesss/v2")
public class Dil {

    @XmlElement(name = "EvidencniUdaje", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TEvidencniUdajeDilu evidencniUdaje;
    @XmlElement(name = "Dokumenty", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TDokumenty dokumenty;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the evidencniUdaje property.
     * 
     * @return
     *     possible object is
     *     {@link TEvidencniUdajeDilu }
     *     
     */
    public TEvidencniUdajeDilu getEvidencniUdaje() {
        return evidencniUdaje;
    }

    /**
     * Sets the value of the evidencniUdaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEvidencniUdajeDilu }
     *     
     */
    public void setEvidencniUdaje(TEvidencniUdajeDilu value) {
        this.evidencniUdaje = value;
    }

    /**
     * Gets the value of the dokumenty property.
     * 
     * @return
     *     possible object is
     *     {@link TDokumenty }
     *     
     */
    public TDokumenty getDokumenty() {
        return dokumenty;
    }

    /**
     * Sets the value of the dokumenty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDokumenty }
     *     
     */
    public void setDokumenty(TDokumenty value) {
        this.dokumenty = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
