//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Bezpečnostní kategorie je opatření spojené s entitou, které podmiňuje nebo definuje pravidla určující podmínky přístupu k ní. Toto opatření se uplatňuje zejména v souvislosti s klasifikací dokumentu, který obsahuje utajovanou informaci, stupněm utajení, jímž je klasifikován (zákon č. 412/2005 Sb.), nebo v souvislosti s označením dokumentu pro omezení přístupu k němu podle jiného právního předpisu, anebo v souvislosti s rozhodnutím organizace (původce) omezit přístup k jím stanoveným kategoriím entit.
 * 
 * <p>Java class for tBezpecnostniKategorie complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tBezpecnostniKategorie">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifikator" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator"/>
 *         &lt;element name="Nazev" type="{http://www.mvcr.cz/nsesss/v2}tNazev"/>
 *         &lt;element name="Komentar" type="{http://www.mvcr.cz/nsesss/v2}tKomentar" minOccurs="0"/>
 *         &lt;element name="Oduvodneni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BezpecnostniStupen" type="{http://www.mvcr.cz/nsesss/v2}tText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tBezpecnostniKategorie", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "identifikator",
    "nazev",
    "komentar",
    "oduvodneni",
    "bezpecnostniStupen"
})
public class TBezpecnostniKategorie {

    @XmlElement(name = "Identifikator", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TIdentifikator identifikator;
    @XmlElement(name = "Nazev", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String nazev;
    @XmlElement(name = "Komentar", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String komentar;
    @XmlElement(name = "Oduvodneni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String oduvodneni;
    @XmlElement(name = "BezpecnostniStupen", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String bezpecnostniStupen;

    /**
     * Gets the value of the identifikator property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentifikator }
     *     
     */
    public TIdentifikator getIdentifikator() {
        return identifikator;
    }

    /**
     * Sets the value of the identifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentifikator }
     *     
     */
    public void setIdentifikator(TIdentifikator value) {
        this.identifikator = value;
    }

    /**
     * Gets the value of the nazev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazev() {
        return nazev;
    }

    /**
     * Sets the value of the nazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazev(String value) {
        this.nazev = value;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomentar(String value) {
        this.komentar = value;
    }

    /**
     * Gets the value of the oduvodneni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOduvodneni() {
        return oduvodneni;
    }

    /**
     * Sets the value of the oduvodneni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOduvodneni(String value) {
        this.oduvodneni = value;
    }

    /**
     * Gets the value of the bezpecnostniStupen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezpecnostniStupen() {
        return bezpecnostniStupen;
    }

    /**
     * Sets the value of the bezpecnostniStupen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezpecnostniStupen(String value) {
        this.bezpecnostniStupen = value;
    }

}
