//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro evidenci údajů o doručení dokumentu.
 * 
 * <p>Java class for tDorucenyDokument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDorucenyDokument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatumVytvoreni" type="{http://www.mvcr.cz/nsesss/v2}tDatum" minOccurs="0"/>
 *         &lt;element name="Autor" type="{http://www.mvcr.cz/nsesss/v2}tOsobyExterni" minOccurs="0"/>
 *         &lt;element name="DatumDoruceni" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="OdesilatelovoEvidencniCislo" type="{http://www.mvcr.cz/nsesss/v2}tEvidencniCislo" minOccurs="0"/>
 *         &lt;element name="DoruceneMnozstvi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Odesilatel" type="{http://www.mvcr.cz/nsesss/v2}tOsobaExterni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDorucenyDokument", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "datumVytvoreni",
    "autor",
    "datumDoruceni",
    "odesilatelovoEvidencniCislo",
    "doruceneMnozstvi",
    "odesilatel"
})
public class TDorucenyDokument {

    @XmlElement(name = "DatumVytvoreni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TDatum datumVytvoreni;
    @XmlElement(name = "Autor", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TOsobyExterni autor;
    @XmlElement(name = "DatumDoruceni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum datumDoruceni;
    @XmlElement(name = "OdesilatelovoEvidencniCislo", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String odesilatelovoEvidencniCislo;
    @XmlElement(name = "DoruceneMnozstvi", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String doruceneMnozstvi;
    @XmlElement(name = "Odesilatel", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOsobaExterni odesilatel;

    /**
     * Gets the value of the datumVytvoreni property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getDatumVytvoreni() {
        return datumVytvoreni;
    }

    /**
     * Sets the value of the datumVytvoreni property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setDatumVytvoreni(TDatum value) {
        this.datumVytvoreni = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link TOsobyExterni }
     *     
     */
    public TOsobyExterni getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsobyExterni }
     *     
     */
    public void setAutor(TOsobyExterni value) {
        this.autor = value;
    }

    /**
     * Gets the value of the datumDoruceni property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getDatumDoruceni() {
        return datumDoruceni;
    }

    /**
     * Sets the value of the datumDoruceni property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setDatumDoruceni(TDatum value) {
        this.datumDoruceni = value;
    }

    /**
     * Gets the value of the odesilatelovoEvidencniCislo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdesilatelovoEvidencniCislo() {
        return odesilatelovoEvidencniCislo;
    }

    /**
     * Sets the value of the odesilatelovoEvidencniCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdesilatelovoEvidencniCislo(String value) {
        this.odesilatelovoEvidencniCislo = value;
    }

    /**
     * Gets the value of the doruceneMnozstvi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoruceneMnozstvi() {
        return doruceneMnozstvi;
    }

    /**
     * Sets the value of the doruceneMnozstvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoruceneMnozstvi(String value) {
        this.doruceneMnozstvi = value;
    }

    /**
     * Gets the value of the odesilatel property.
     * 
     * @return
     *     possible object is
     *     {@link TOsobaExterni }
     *     
     */
    public TOsobaExterni getOdesilatel() {
        return odesilatel;
    }

    /**
     * Sets the value of the odesilatel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsobaExterni }
     *     
     */
    public void setOdesilatel(TOsobaExterni value) {
        this.odesilatel = value;
    }

}
