//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro evidenci spisů nebo dokumentů.
 * 
 * <p>Java class for tEvidence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEvidence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EvidencniCislo" type="{http://www.mvcr.cz/nsesss/v2}tEvidencniCislo"/>
 *         &lt;element name="PoradoveCislo" type="{http://www.mvcr.cz/nsesss/v2}tPoradoveCislo" minOccurs="0"/>
 *         &lt;element name="UrceneCasoveObdobi" type="{http://www.mvcr.cz/nsesss/v2}tUrceneCasoveObdobi"/>
 *         &lt;element name="NazevEvidenceDokumentu" type="{http://www.mvcr.cz/nsesss/v2}tNazev"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEvidence", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "evidencniCislo",
    "poradoveCislo",
    "urceneCasoveObdobi",
    "nazevEvidenceDokumentu"
})
public class TEvidence {

    @XmlElement(name = "EvidencniCislo", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String evidencniCislo;
    @XmlElement(name = "PoradoveCislo", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected Integer poradoveCislo;
    @XmlElement(name = "UrceneCasoveObdobi", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TUrceneCasoveObdobi urceneCasoveObdobi;
    @XmlElement(name = "NazevEvidenceDokumentu", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String nazevEvidenceDokumentu;

    /**
     * Gets the value of the evidencniCislo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvidencniCislo() {
        return evidencniCislo;
    }

    /**
     * Sets the value of the evidencniCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvidencniCislo(String value) {
        this.evidencniCislo = value;
    }

    /**
     * Gets the value of the poradoveCislo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPoradoveCislo() {
        return poradoveCislo;
    }

    /**
     * Sets the value of the poradoveCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPoradoveCislo(Integer value) {
        this.poradoveCislo = value;
    }

    /**
     * Gets the value of the urceneCasoveObdobi property.
     * 
     * @return
     *     possible object is
     *     {@link TUrceneCasoveObdobi }
     *     
     */
    public TUrceneCasoveObdobi getUrceneCasoveObdobi() {
        return urceneCasoveObdobi;
    }

    /**
     * Sets the value of the urceneCasoveObdobi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUrceneCasoveObdobi }
     *     
     */
    public void setUrceneCasoveObdobi(TUrceneCasoveObdobi value) {
        this.urceneCasoveObdobi = value;
    }

    /**
     * Gets the value of the nazevEvidenceDokumentu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazevEvidenceDokumentu() {
        return nazevEvidenceDokumentu;
    }

    /**
     * Sets the value of the nazevEvidenceDokumentu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazevEvidenceDokumentu(String value) {
        this.nazevEvidenceDokumentu = value;
    }

}
