//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro popis konverze dokumentu nebo komponenty z analogové podoby do digitální podoby (AD) nebo z podoby digitální do podoby analogové (DA).
 * 
 * <p>Java class for tKonverzeAD-DA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tKonverzeAD-DA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Vystup" type="{http://www.mvcr.cz/nsesss/v2}tVystup" maxOccurs="unbounded"/>
 *         &lt;sequence>
 *           &lt;element name="Oduvodneni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="AutorizovanaKonverze" type="{http://www.mvcr.cz/nsesss/v2}tLogicky"/>
 *           &lt;element name="OdkazVstup" type="{http://www.mvcr.cz/nsesss/v2}tOdkaz"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tKonverzeAD-DA", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "vystup",
    "oduvodneni",
    "autorizovanaKonverze",
    "odkazVstup"
})
public class TKonverzeADDA {

    @XmlElement(name = "Vystup", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected List<TVystup> vystup;
    @XmlElement(name = "Oduvodneni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String oduvodneni;
    @XmlElement(name = "AutorizovanaKonverze", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TLogicky autorizovanaKonverze;
    @XmlElement(name = "OdkazVstup", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TOdkaz odkazVstup;

    /**
     * Gets the value of the vystup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vystup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVystup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TVystup }
     * 
     * 
     */
    public List<TVystup> getVystup() {
        if (vystup == null) {
            vystup = new ArrayList<TVystup>();
        }
        return this.vystup;
    }

    /**
     * Gets the value of the oduvodneni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOduvodneni() {
        return oduvodneni;
    }

    /**
     * Sets the value of the oduvodneni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOduvodneni(String value) {
        this.oduvodneni = value;
    }

    /**
     * Gets the value of the autorizovanaKonverze property.
     * 
     * @return
     *     possible object is
     *     {@link TLogicky }
     *     
     */
    public TLogicky getAutorizovanaKonverze() {
        return autorizovanaKonverze;
    }

    /**
     * Sets the value of the autorizovanaKonverze property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLogicky }
     *     
     */
    public void setAutorizovanaKonverze(TLogicky value) {
        this.autorizovanaKonverze = value;
    }

    /**
     * Gets the value of the odkazVstup property.
     * 
     * @return
     *     possible object is
     *     {@link TOdkaz }
     *     
     */
    public TOdkaz getOdkazVstup() {
        return odkazVstup;
    }

    /**
     * Sets the value of the odkazVstup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOdkaz }
     *     
     */
    public void setOdkazVstup(TOdkaz value) {
        this.odkazVstup = value;
    }

}
