//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Časové údaje evidující počátek a konec platnosti spisového plánu.
 * 
 * <p>Java class for tManipulaceSpisovyPlan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tManipulaceSpisovyPlan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatumOtevreni" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="DatumUzavreni" type="{http://www.mvcr.cz/nsesss/v2}tDatum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tManipulaceSpisovyPlan", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "datumOtevreni",
    "datumUzavreni"
})
public class TManipulaceSpisovyPlan {

    @XmlElement(name = "DatumOtevreni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum datumOtevreni;
    @XmlElement(name = "DatumUzavreni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TDatum datumUzavreni;

    /**
     * Gets the value of the datumOtevreni property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getDatumOtevreni() {
        return datumOtevreni;
    }

    /**
     * Sets the value of the datumOtevreni property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setDatumOtevreni(TDatum value) {
        this.datumOtevreni = value;
    }

    /**
     * Gets the value of the datumUzavreni property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getDatumUzavreni() {
        return datumUzavreni;
    }

    /**
     * Sets the value of the datumUzavreni property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setDatumUzavreni(TDatum value) {
        this.datumUzavreni = value;
    }

}
