//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro indikaci nezbytných dokumentů (dokumenty zásadního významu, které jsou nezbytné pro schopnost organizace pokračovat v pracovní činnosti s přihlédnutím k vytvořeným předpokladům vypořádat se s následky mimořádných událostí nebo krizových stavů, anebo ochránit své dlouhodobé ekonomické a právní zájmy) a dokumentů v analogové podobě v rámci entity.
 * 
 * <p>Java class for tManipulace complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tManipulace">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NezbytnyDokument" type="{http://www.mvcr.cz/nsesss/v2}tLogicky"/>
 *         &lt;element name="AnalogovyDokument" type="{http://www.mvcr.cz/nsesss/v2}tLogicky"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tManipulace", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "nezbytnyDokument",
    "analogovyDokument"
})
@XmlSeeAlso({
    TManipulaceDokumentu.class,
    TManipulaceSeskupeni.class
})
public class TManipulace {

    @XmlElement(name = "NezbytnyDokument", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TLogicky nezbytnyDokument;
    @XmlElement(name = "AnalogovyDokument", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TLogicky analogovyDokument;

    /**
     * Gets the value of the nezbytnyDokument property.
     * 
     * @return
     *     possible object is
     *     {@link TLogicky }
     *     
     */
    public TLogicky getNezbytnyDokument() {
        return nezbytnyDokument;
    }

    /**
     * Sets the value of the nezbytnyDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLogicky }
     *     
     */
    public void setNezbytnyDokument(TLogicky value) {
        this.nezbytnyDokument = value;
    }

    /**
     * Gets the value of the analogovyDokument property.
     * 
     * @return
     *     possible object is
     *     {@link TLogicky }
     *     
     */
    public TLogicky getAnalogovyDokument() {
        return analogovyDokument;
    }

    /**
     * Sets the value of the analogovyDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLogicky }
     *     
     */
    public void setAnalogovyDokument(TLogicky value) {
        this.analogovyDokument = value;
    }

}
