//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro mateřské entity dokumentu.
 * 
 * <p>Java class for tMaterskeEntityDokumentu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tMaterskeEntityDokumentu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VecnaSkupina" type="{http://www.mvcr.cz/nsesss/v2}tVecnaSkupina"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tMaterskeEntityDokumentu", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "vecnaSkupina"
})
public class TMaterskeEntityDokumentu {

    @XmlElement(name = "VecnaSkupina", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TVecnaSkupina vecnaSkupina;

    /**
     * Gets the value of the vecnaSkupina property.
     * 
     * @return
     *     possible object is
     *     {@link TVecnaSkupina }
     *     
     */
    public TVecnaSkupina getVecnaSkupina() {
        return vecnaSkupina;
    }

    /**
     * Sets the value of the vecnaSkupina property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVecnaSkupina }
     *     
     */
    public void setVecnaSkupina(TVecnaSkupina value) {
        this.vecnaSkupina = value;
    }

}
