//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOvereniCertifikatu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOvereniCertifikatu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PosuzovanyOkamzik" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="PlatnostBezpecnostnihoPrvkuCertifikatu" type="{http://www.mvcr.cz/nsesss/v2}tVysledekOvereni"/>
 *         &lt;element name="CisloSeznamuCRL" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator"/>
 *         &lt;element name="StavRevokace" type="{http://www.mvcr.cz/nsesss/v2}tLogicky"/>
 *         &lt;element name="PlatnostBezpecnostnihoPrvkuCRL" type="{http://www.mvcr.cz/nsesss/v2}tVysledekOvereni"/>
 *         &lt;element name="PlatnostCertifikacniCesty" type="{http://www.mvcr.cz/nsesss/v2}tVysledekOvereni"/>
 *         &lt;element name="CasOvereni" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="PlatnostCertifikatu" type="{http://www.mvcr.cz/nsesss/v2}tVysledekOvereni"/>
 *         &lt;element name="Overovatel" type="{http://www.mvcr.cz/nsesss/v2}tOsobaInterni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOvereniCertifikatu", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "posuzovanyOkamzik",
    "platnostBezpecnostnihoPrvkuCertifikatu",
    "cisloSeznamuCRL",
    "stavRevokace",
    "platnostBezpecnostnihoPrvkuCRL",
    "platnostCertifikacniCesty",
    "casOvereni",
    "platnostCertifikatu",
    "overovatel"
})
public class TOvereniCertifikatu {

    @XmlElement(name = "PosuzovanyOkamzik", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum posuzovanyOkamzik;
    @XmlElement(name = "PlatnostBezpecnostnihoPrvkuCertifikatu", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TVysledekOvereni platnostBezpecnostnihoPrvkuCertifikatu;
    @XmlElement(name = "CisloSeznamuCRL", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TIdentifikator cisloSeznamuCRL;
    @XmlElement(name = "StavRevokace", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TLogicky stavRevokace;
    @XmlElement(name = "PlatnostBezpecnostnihoPrvkuCRL", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TVysledekOvereni platnostBezpecnostnihoPrvkuCRL;
    @XmlElement(name = "PlatnostCertifikacniCesty", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TVysledekOvereni platnostCertifikacniCesty;
    @XmlElement(name = "CasOvereni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum casOvereni;
    @XmlElement(name = "PlatnostCertifikatu", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TVysledekOvereni platnostCertifikatu;
    @XmlElement(name = "Overovatel", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOsobaInterni overovatel;

    /**
     * Gets the value of the posuzovanyOkamzik property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getPosuzovanyOkamzik() {
        return posuzovanyOkamzik;
    }

    /**
     * Sets the value of the posuzovanyOkamzik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setPosuzovanyOkamzik(TDatum value) {
        this.posuzovanyOkamzik = value;
    }

    /**
     * Gets the value of the platnostBezpecnostnihoPrvkuCertifikatu property.
     * 
     * @return
     *     possible object is
     *     {@link TVysledekOvereni }
     *     
     */
    public TVysledekOvereni getPlatnostBezpecnostnihoPrvkuCertifikatu() {
        return platnostBezpecnostnihoPrvkuCertifikatu;
    }

    /**
     * Sets the value of the platnostBezpecnostnihoPrvkuCertifikatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVysledekOvereni }
     *     
     */
    public void setPlatnostBezpecnostnihoPrvkuCertifikatu(TVysledekOvereni value) {
        this.platnostBezpecnostnihoPrvkuCertifikatu = value;
    }

    /**
     * Gets the value of the cisloSeznamuCRL property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentifikator }
     *     
     */
    public TIdentifikator getCisloSeznamuCRL() {
        return cisloSeznamuCRL;
    }

    /**
     * Sets the value of the cisloSeznamuCRL property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentifikator }
     *     
     */
    public void setCisloSeznamuCRL(TIdentifikator value) {
        this.cisloSeznamuCRL = value;
    }

    /**
     * Gets the value of the stavRevokace property.
     * 
     * @return
     *     possible object is
     *     {@link TLogicky }
     *     
     */
    public TLogicky getStavRevokace() {
        return stavRevokace;
    }

    /**
     * Sets the value of the stavRevokace property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLogicky }
     *     
     */
    public void setStavRevokace(TLogicky value) {
        this.stavRevokace = value;
    }

    /**
     * Gets the value of the platnostBezpecnostnihoPrvkuCRL property.
     * 
     * @return
     *     possible object is
     *     {@link TVysledekOvereni }
     *     
     */
    public TVysledekOvereni getPlatnostBezpecnostnihoPrvkuCRL() {
        return platnostBezpecnostnihoPrvkuCRL;
    }

    /**
     * Sets the value of the platnostBezpecnostnihoPrvkuCRL property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVysledekOvereni }
     *     
     */
    public void setPlatnostBezpecnostnihoPrvkuCRL(TVysledekOvereni value) {
        this.platnostBezpecnostnihoPrvkuCRL = value;
    }

    /**
     * Gets the value of the platnostCertifikacniCesty property.
     * 
     * @return
     *     possible object is
     *     {@link TVysledekOvereni }
     *     
     */
    public TVysledekOvereni getPlatnostCertifikacniCesty() {
        return platnostCertifikacniCesty;
    }

    /**
     * Sets the value of the platnostCertifikacniCesty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVysledekOvereni }
     *     
     */
    public void setPlatnostCertifikacniCesty(TVysledekOvereni value) {
        this.platnostCertifikacniCesty = value;
    }

    /**
     * Gets the value of the casOvereni property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getCasOvereni() {
        return casOvereni;
    }

    /**
     * Sets the value of the casOvereni property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setCasOvereni(TDatum value) {
        this.casOvereni = value;
    }

    /**
     * Gets the value of the platnostCertifikatu property.
     * 
     * @return
     *     possible object is
     *     {@link TVysledekOvereni }
     *     
     */
    public TVysledekOvereni getPlatnostCertifikatu() {
        return platnostCertifikatu;
    }

    /**
     * Sets the value of the platnostCertifikatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVysledekOvereni }
     *     
     */
    public void setPlatnostCertifikatu(TVysledekOvereni value) {
        this.platnostCertifikatu = value;
    }

    /**
     * Gets the value of the overovatel property.
     * 
     * @return
     *     possible object is
     *     {@link TOsobaInterni }
     *     
     */
    public TOsobaInterni getOverovatel() {
        return overovatel;
    }

    /**
     * Sets the value of the overovatel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsobaInterni }
     *     
     */
    public void setOverovatel(TOsobaInterni value) {
        this.overovatel = value;
    }

}
