//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Metadatový kontejner pro zaznamenání doručení nebo vzniku dokumentu.
 * 
 * <p>Java class for tPuvodDokumentu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPuvodDokumentu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="DorucenyDokument" type="{http://www.mvcr.cz/nsesss/v2}tDorucenyDokument"/>
 *         &lt;element name="VlastniDokument" type="{http://www.mvcr.cz/nsesss/v2}tVlastniDokument"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPuvodDokumentu", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "dorucenyDokument",
    "vlastniDokument"
})
public class TPuvodDokumentu {

    @XmlElement(name = "DorucenyDokument", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TDorucenyDokument dorucenyDokument;
    @XmlElement(name = "VlastniDokument", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TVlastniDokument vlastniDokument;

    /**
     * Gets the value of the dorucenyDokument property.
     * 
     * @return
     *     possible object is
     *     {@link TDorucenyDokument }
     *     
     */
    public TDorucenyDokument getDorucenyDokument() {
        return dorucenyDokument;
    }

    /**
     * Sets the value of the dorucenyDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDorucenyDokument }
     *     
     */
    public void setDorucenyDokument(TDorucenyDokument value) {
        this.dorucenyDokument = value;
    }

    /**
     * Gets the value of the vlastniDokument property.
     * 
     * @return
     *     possible object is
     *     {@link TVlastniDokument }
     *     
     */
    public TVlastniDokument getVlastniDokument() {
        return vlastniDokument;
    }

    /**
     * Sets the value of the vlastniDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVlastniDokument }
     *     
     */
    public void setVlastniDokument(TVlastniDokument value) {
        this.vlastniDokument = value;
    }

}
