//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro identifikaci právnické nebo fyzické osoby a pro uvedení její poštovní adresy (adresy pro doručování) nebo elektronického kontaktu. Tato osoba není identická s organizací, která tato metadata vytváří, nebo není v zaměstnaneckém poměru k této organizaci.
 * 
 * <p>Java class for tSubjektExterni complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSubjektExterni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="IdentifikatorOrganizace" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator"/>
 *           &lt;element name="NazevOrganizace" type="{http://www.mvcr.cz/nsesss/v2}tNazev"/>
 *           &lt;element name="IdentifikatorFyzickeOsoby" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator" minOccurs="0"/>
 *           &lt;element name="NazevFyzickeOsoby" type="{http://www.mvcr.cz/nsesss/v2}tNazev" minOccurs="0"/>
 *           &lt;element name="OrganizacniUtvar" type="{http://www.mvcr.cz/nsesss/v2}tText" minOccurs="0"/>
 *           &lt;element name="PracovniPozice" type="{http://www.mvcr.cz/nsesss/v2}tText" minOccurs="0"/>
 *           &lt;element name="SidloOrganizace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="ElektronickyKontakt" type="{http://www.mvcr.cz/nsesss/v2}tText" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="IdentifikatorFyzickeOsoby" type="{http://www.mvcr.cz/nsesss/v2}tIdentifikator" minOccurs="0"/>
 *           &lt;element name="NazevFyzickeOsoby" type="{http://www.mvcr.cz/nsesss/v2}tNazev"/>
 *           &lt;element name="PostovniAdresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="ElektronickyKontakt" type="{http://www.mvcr.cz/nsesss/v2}tText"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSubjektExterni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "content"
})
public class TSubjektExterni {

    @XmlElementRefs({
        @XmlElementRef(name = "ElektronickyKontakt", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
        @XmlElementRef(name = "IdentifikatorFyzickeOsoby", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
        @XmlElementRef(name = "PracovniPozice", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
        @XmlElementRef(name = "NazevFyzickeOsoby", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
        @XmlElementRef(name = "OrganizacniUtvar", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
        @XmlElementRef(name = "IdentifikatorOrganizace", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
        @XmlElementRef(name = "NazevOrganizace", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
        @XmlElementRef(name = "SidloOrganizace", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class),
        @XmlElementRef(name = "PostovniAdresa", namespace = "http://www.mvcr.cz/nsesss/v2", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "IdentifikatorFyzickeOsoby" is used by two different parts of a schema. See: 
     * line 1062 of file:/mnt/share/development/incad/das/editor/proarc-desa/src/main/resources/cz/cas/lib/proarc/desa/nsesss2/nsesss2.xsd
     * line 1054 of file:/mnt/share/development/incad/das/editor/proarc-desa/src/main/resources/cz/cas/lib/proarc/desa/nsesss2/nsesss2.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TIdentifikator }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TIdentifikator }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
