//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro zatřídění entity do hierarchie spisového plánu. Prvek obsahuje údaje o jednoduchém spisovém znaku a plně určeném spisovém znaku entity.
 * 
 * <p>Java class for tTrideni complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTrideni">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JednoduchySpisovyZnak" type="{http://www.mvcr.cz/nsesss/v2}tJednoduchySpisovyZnak"/>
 *         &lt;element name="PlneUrcenySpisovyZnak" type="{http://www.mvcr.cz/nsesss/v2}tPlneUrcenySpisovyZnak"/>
 *         &lt;element name="Oduvodneni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTrideni", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "jednoduchySpisovyZnak",
    "plneUrcenySpisovyZnak",
    "oduvodneni"
})
@XmlSeeAlso({
    TTrideniSoucasti.class,
    TTrideniVecneSkupiny.class,
    TTrideniDilu.class,
    TTrideniTypovehoSpisu.class,
    TTrideniDokumentu.class,
    TTrideniSpisu.class
})
public class TTrideni {

    @XmlElement(name = "JednoduchySpisovyZnak", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String jednoduchySpisovyZnak;
    @XmlElement(name = "PlneUrcenySpisovyZnak", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected String plneUrcenySpisovyZnak;
    @XmlElement(name = "Oduvodneni", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String oduvodneni;

    /**
     * Gets the value of the jednoduchySpisovyZnak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJednoduchySpisovyZnak() {
        return jednoduchySpisovyZnak;
    }

    /**
     * Sets the value of the jednoduchySpisovyZnak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJednoduchySpisovyZnak(String value) {
        this.jednoduchySpisovyZnak = value;
    }

    /**
     * Gets the value of the plneUrcenySpisovyZnak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlneUrcenySpisovyZnak() {
        return plneUrcenySpisovyZnak;
    }

    /**
     * Sets the value of the plneUrcenySpisovyZnak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlneUrcenySpisovyZnak(String value) {
        this.plneUrcenySpisovyZnak = value;
    }

    /**
     * Gets the value of the oduvodneni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOduvodneni() {
        return oduvodneni;
    }

    /**
     * Sets the value of the oduvodneni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOduvodneni(String value) {
        this.oduvodneni = value;
    }

}
