//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro zatřídění dokumentu do hierarchie spisového plánu.
 * 
 * <p>Java class for tTrideniDokumentu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTrideniDokumentu">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mvcr.cz/nsesss/v2}tTrideni">
 *       &lt;sequence>
 *         &lt;element name="TypDokumentu" type="{http://www.mvcr.cz/nsesss/v2}tTypDokumentu"/>
 *         &lt;element name="MaterskeEntity" type="{http://www.mvcr.cz/nsesss/v2}tMaterskeEntityDokumentu" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTrideniDokumentu", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "typDokumentu",
    "materskeEntity"
})
public class TTrideniDokumentu
    extends TTrideni
{

    @XmlElement(name = "TypDokumentu", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TTypDokumentu typDokumentu;
    @XmlElement(name = "MaterskeEntity", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected TMaterskeEntityDokumentu materskeEntity;

    /**
     * Gets the value of the typDokumentu property.
     * 
     * @return
     *     possible object is
     *     {@link TTypDokumentu }
     *     
     */
    public TTypDokumentu getTypDokumentu() {
        return typDokumentu;
    }

    /**
     * Sets the value of the typDokumentu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTypDokumentu }
     *     
     */
    public void setTypDokumentu(TTypDokumentu value) {
        this.typDokumentu = value;
    }

    /**
     * Gets the value of the materskeEntity property.
     * 
     * @return
     *     possible object is
     *     {@link TMaterskeEntityDokumentu }
     *     
     */
    public TMaterskeEntityDokumentu getMaterskeEntity() {
        return materskeEntity;
    }

    /**
     * Sets the value of the materskeEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMaterskeEntityDokumentu }
     *     
     */
    public void setMaterskeEntity(TMaterskeEntityDokumentu value) {
        this.materskeEntity = value;
    }

}
