//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Sada elementů pro evidenci údajů o vzniku vlastního dokumentu organizace.
 * 
 * <p>Java class for tVlastniDokument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tVlastniDokument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatumVytvoreni" type="{http://www.mvcr.cz/nsesss/v2}tDatum"/>
 *         &lt;element name="VytvoreneMnozstvi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Autor" type="{http://www.mvcr.cz/nsesss/v2}tOsobyInterni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tVlastniDokument", namespace = "http://www.mvcr.cz/nsesss/v2", propOrder = {
    "datumVytvoreni",
    "vytvoreneMnozstvi",
    "autor"
})
public class TVlastniDokument {

    @XmlElement(name = "DatumVytvoreni", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TDatum datumVytvoreni;
    @XmlElement(name = "VytvoreneMnozstvi", namespace = "http://www.mvcr.cz/nsesss/v2")
    protected String vytvoreneMnozstvi;
    @XmlElement(name = "Autor", namespace = "http://www.mvcr.cz/nsesss/v2", required = true)
    protected TOsobyInterni autor;

    /**
     * Gets the value of the datumVytvoreni property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getDatumVytvoreni() {
        return datumVytvoreni;
    }

    /**
     * Sets the value of the datumVytvoreni property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setDatumVytvoreni(TDatum value) {
        this.datumVytvoreni = value;
    }

    /**
     * Gets the value of the vytvoreneMnozstvi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVytvoreneMnozstvi() {
        return vytvoreneMnozstvi;
    }

    /**
     * Sets the value of the vytvoreneMnozstvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVytvoreneMnozstvi(String value) {
        this.vytvoreneMnozstvi = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link TOsobyInterni }
     *     
     */
    public TOsobyInterni getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsobyInterni }
     *     
     */
    public void setAutor(TOsobyInterni value) {
        this.autor = value;
    }

}
