//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.21 at 01:10:09 AM CET 
//


package cz.cas.lib.proarc.desa.nsesss2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tVysledekOvereni.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tVysledekOvereni">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="platný"/>
 *     &lt;enumeration value="neplatný"/>
 *     &lt;enumeration value="platnost nelze posoudit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tVysledekOvereni", namespace = "http://www.mvcr.cz/nsesss/v2")
@XmlEnum
public enum TVysledekOvereni {

    @XmlEnumValue("platn\u00fd")
    PLATNÝ("platn\u00fd"),
    @XmlEnumValue("neplatn\u00fd")
    NEPLATNÝ("neplatn\u00fd"),
    @XmlEnumValue("platnost nelze posoudit")
    PLATNOST_NELZE_POSOUDIT("platnost nelze posoudit");
    private final String value;

    TVysledekOvereni(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TVysledekOvereni fromValue(String v) {
        for (TVysledekOvereni c: TVysledekOvereni.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
